### ISSUE TITLE
[Feature] add listPartitions and dropPartitions in paimon Catalog

### ISSUE THREAD

**Issue by leaves12138** [apache/incubator-paimon#1004]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

1、Paimon data lake support partition function but Catalog does not support partition actions

2、Flink Catalog has listPartitions function

### Solution

1、add listPartitions function in Catalog

2、add dropPartitions function in Catalog

### Anything else?

listPartition function could finish by Projections, pass the avro schema to the avro reader, get rid of redundant bytes decoding.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
Related issues: #747

**Comment by SteNicholas** [comment]
@leaves12138, duplicated with #747. Closed.
