### ISSUE TITLE
[Feature] Support Apache Impala integration with Paimon

### ISSUE THREAD

**Issue by 68118451** [apache/incubator-paimon#1013]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

we can use Impala to query the paimon table

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by s7monk** [comment]
Will you contribute this pr？

**Comment by Alibaba-HZY** [comment]
I've started a discussion in support of paimon on the impala community.

**Comment by SteNicholas** [comment]
@68118451, it's better to create issue for integration with Paimon in Impala community. Meanwhile, @Alibaba-HZY has already started discussion thread for the integration.
