### ISSUE TITLE
[Feature] CDC Ingestion:  add a prefix configuration option to determine the form of 'prefix + table name' when the table does not exist

### ISSUE THREAD

**Issue by www2388258980** [apache/incubator-paimon#1017]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

document: https://paimon.apache.org/docs/master/how-to/cdc-ingestion/

The ODS and database table names may not be consistent, 
there is generally a uniform prefix to indicate a business system,
Therefore, when synchronizing the cdc library, can you add a prefix configuration option to determine the form of 'prefix + table name' when the table does not exist?

eg:  
--table-conf table_prefix=src_public_    

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Thanks @www2388258980 for reporting, please use English.
