### ISSUE TITLE
[Feature] add mysql8 support for mysql cdc action test case 

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/incubator-paimon#1027]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

like flink cdc ,we should add the mysql8 support for mysql cdc action test case 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by MurderWind** [comment]
i am  a newcomer . can i try to take this ?

**Comment by zhuangchong** [comment]
Mysql8 cdc action test case already exists. `MySql80E2eTest` #824
