### ISSUE TITLE
[Bug] HiveWriteITCase.testInsertAllSupportedTypes is unstable

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#1039]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.4

### Compute Engine

hive

### Minimal reproduce step

tests

### What doesn't meet your expectations?

https://github.com/apache/incubator-paimon/actions/runs/4808128540/jobs/8558676893

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Alibaba-HZY** [comment]
Please assign this issue to me. I will fixed it soon
