### ISSUE TITLE
[Feature][FileSystem] Support huawei cloud OBS

### ISSUE THREAD

**Issue by kim-up** [apache/incubator-paimon#1042]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Paimon support huawei cloud  obs fileSystem.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
The related PR has been closed, I will close this issue.
