### ISSUE TITLE
[Feature] When records have same sequence number , the latter one is used as the final result.

### ISSUE THREAD

**Issue by lppsuixn** [apache/incubator-paimon#1050]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

When consuming CDC  data, we use sequence.field to avoid disorder. However, since MySQL's execution time is at the level of seconds, there may be issues with the same ID and same execution time.

### Solution

add an auto-incrementing "inner-sequence-number" field in the SystemColumns. When the sequence numbers are the same, can compare the inner-sequence-numbers to determine the order.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jameswangchen** [comment]
I have the same problem.It will cause the data to be incorrect.

**Comment by JingsongLi** [comment]
Thanks @lppsuixn and @jameswangchen for reporting!

Consider paimon sink to add an option so that if the sequence_number provided does not meet the precision, sink goes and makes up a nanos after it.

**Comment by schnappi17** [comment]
@JingsongLi I'm willing to task this, could you assign it to me please?

**Comment by JingsongLi** [comment]
> @JingsongLi I'm willing to task this, could you assign it to me please?

Okay, can you think about how to design this API first? How to splice the user's sequence_field and nano_time?

**Comment by schnappi17** [comment]
> > @JingsongLi I'm willing to task this, could you assign it to me please?
> 
> Okay, can you think about how to design this API first? How to splice the user's sequence_field and nano_time?

Yes, thanks for reminding~I'll think about it.

**Comment by jameswangchen** [comment]
@schnappi17  Hello,what is the status of this issue?

**Comment by schnappi17** [comment]
> @schnappi17 Hello,what is the status of this issue?

Hi @jameswangchen, I'm working on this, will submit PR this week.
