### ISSUE TITLE
[Bug] `PartitionExpireTest.testFilterCommittedAfterExpiring` is not stable

### ISSUE THREAD

**Issue by liugddx** [apache/incubator-paimon#1058]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

dev

### Compute Engine

test case

### Minimal reproduce step

-

### What doesn't meet your expectations?

https://github.com/apache/incubator-paimon/actions/runs/4878255889/jobs/8703735487

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Thanks @liugddx , I will fix this.

**Comment by JingsongLi** [comment]
Fixed in https://github.com/apache/incubator-paimon/commit/f8613477e5cbaac16377fd3212b35f6c78666378
