### ISSUE TITLE
[Feature] add UDF function for column on flink cdc sync action

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/incubator-paimon#1077]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

During sync mysql data to paimon, we need to encrypt some sensitive fields, such as mobile phone number and ID number. 

So I think we should add UDF functions to some columns for encryption .  For example my phone number is `13812345678`, which will be converted to `138xxxxxxxx`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
This is related to https://github.com/apache/incubator-paimon/issues/1038

**Comment by zhuangchong** [comment]
This PR has been completed, I will close this issue.
