### ISSUE TITLE
[Feature] Check conflict for option "write-mode" and "changelog-producer"

### ISSUE THREAD

**Issue by nonggialiang** [apache/incubator-paimon#1097]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

For now,  the options provided by "write-mode" and "changelog-producer" is not completely compatible.
For example, when "write-mode" is set to "append-only",  the other "changelog-producer" should be ignore because no changelog will be produced at all.
But now, user can make a mistake by setting "write-mode"="append-only" and "changelog-producer" = "input/full-compaction" at the same time, which will lead to mismatched and confusing behaviors at the writer side and reader side :  streaming writer produces no changelog file and continus-reader is looking for changelog file for incremental read and produce empty result.

### Solution

Make a validation of the combination of options provided for a table ?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by s7monk** [comment]
I can try this ticket,please assign this issue to me. @JingsongLi

**Comment by JingsongLi** [comment]
> I can try this ticket,please assign this issue to me. @JingsongLi

Oh, sorry, @zhangjun0x01 already finished this issue.
