### ISSUE TITLE
[Feature] Support Create Database As(CDAS) for CDC Ingestion

### ISSUE THREAD

**Issue by qidian99** [apache/incubator-paimon#1125]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently in order to use cdc ingestion to sync databases, user has to submit a MySqlSyncDatabaseAction in a Flink DataStream job or use flink run command.

I would be awesome if this can be achieved using Flink SQL.

### Solution

I propose sth like the following CTAS and CDAS syntax when syncing MySQL databases to Apache Hudi:
![image](https://github.com/apache/incubator-paimon/assets/20527912/16407dcd-8fbc-41f8-b409-0ddd4b39df0e)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
This could be in Flink side, similar FLIP is https://lists.apache.org/thread/qt6gl08g42h0ypgkovkktbglqr4d8c32
