### ISSUE TITLE
[Feature] Support rollback to snapshot that rollback a table to a specific snapshot ID

### ISSUE THREAD

**Issue by SteNicholas** [apache/incubator-paimon#1128]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

At present, when certain snapshot is destroyed, Paimon doesn't support rollback a table to a specific snapshot ID which may cause the table unavailable.

### Solution

We could support rollback to snapshot that rollback a table to a specific snapshot ID.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by FangYongs** [comment]
fixed with #1179
