### ISSUE TITLE
[Feature] Support month, day, and hour expressions for cdc synchronizing tables action

### ISSUE THREAD

**Issue by yuzelin** [apache/incubator-paimon#1141]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently, cdc synchronizing tables action support computed column. We can support more expressions:
month: extract month from date column
day：extract day from date column
hour：extract hour from date or time column

### Solution

Please reference the implementation of year:
#1109

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ShockleysxX** [comment]
Hi, @yuzelin, I am new to the community, could you assign this task to me, I will do my best to complete it.

**Comment by yuzelin** [comment]
@ShockleysxX Sure. Feel free to contact to me if you have any question.

**Comment by tsreaper** [comment]
Hi @ShockleysxX , are you still working on this issue? If we hear no reply by the end of this week we'll have to unassign you from this task.

**Comment by pizhihui** [comment]
Hi, @ShockleysxX @tsreaper ,I wan to try to fix it。
