### ISSUE TITLE
[Feature] Support for query manifests

### ISSUE THREAD

**Issue by xwmr-max** [apache/incubator-paimon#1154]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Paimon currently supports query the table  snapshots, schemas, options,  and so on , but does not support query table manifests.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Let's do it~

**Comment by schnappi17** [comment]
Can I take this if it's suspended?

**Comment by xwmr-max** [comment]
> Can I take this if it's suspended? @JingsongLi @xwmr-max

Recently, due to internal work, this PR has been delayed. I will submit this PR as soon as possible.
