### ISSUE TITLE
[Feature] Support the metadata management

### ISSUE THREAD

**Issue by xwmr-max** [apache/incubator-paimon#1155]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Support the metadata management, such as the expire snapshots,the rewrite manifests,and so on.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
For Flink, maybe the only way is adding Actions.
For Spark, we can add procedures after https://github.com/apache/incubator-paimon/pull/581

**Comment by xwmr-max** [comment]
I will write actions in flink first, and as for spark, I will add related abilities after #581 @SteNicholas .

**Comment by JingsongLi** [comment]
> I will write actions in flink first, and as for spark, I will add related abilities after #581 @SteNicholas .

Thanks @xwmr-max ! Feel free to open PRs.
