### ISSUE TITLE
[Feature] [Java-api][Catalog]Get all the table information under catalog

### ISSUE THREAD

**Issue by liugddx** [apache/incubator-paimon#1176]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Get all the table information under catalog

### Solution

1. Add listTables in `org.apache.paimon.catalog.Catalog` and return `List<Identifier>`
```
List<Identifier>listTables() throws TableNotExistException;
```
2. Implement corresponding logic in `FileSystemCatalog` and `HiveCatalog`

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Did you refer to anything?
This method looks not so good. (reason replied in PR)

**Comment by zhuangchong** [comment]
This related PR is closed, I will close this issue first, if you have questions, you can open this issue again.
