### ISSUE TITLE
[Feature] Add AlwaysTrue and AlwaysFalse predicate for paimon

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/incubator-paimon#1180]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Add AlwaysTrue and AlwaysFalse predicate for paimon so that we can deal some sql like `select * from mytable where 1=1`

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by yuxuan-luo** [comment]
i want to pick it
