### ISSUE TITLE
[Bug] MySQL E2E tests often timeout and fail

### ISSUE THREAD

**Issue by qidian99** [apache/incubator-paimon#1195]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5-SNAPSHOT

### Compute Engine

Flink

### Minimal reproduce step

![image](https://github.com/apache/incubator-paimon/assets/20527912/10450402-542b-46a8-9ee1-171f18b116ab)

### What doesn't meet your expectations?

![image](https://github.com/apache/incubator-paimon/assets/20527912/0a7dba2f-961f-4697-8699-09035091e7e0)
When running MySqlE2eTest, it often blocks on the above line and not writing data. After 60 seconds, the test timeouts and fails.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by qidian99** [comment]
Tried setting timeout to be 600 retries, still not working. The source coordinator in stuck after receiving split request.

![image](https://github.com/apache/incubator-paimon/assets/20527912/f77961a4-f120-4434-8c8c-17cb2262c2a7)

**Comment by zhuangchong** [comment]
This related PR is closed, I will close this issue first, if you have questions, you can open this issue again.
