### ISSUE TITLE
[Bug] Hive cannot query the timestamp field of the paimon table

### ISSUE THREAD

**Issue by Deeservent** [apache/incubator-paimon#1198]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

paimon-hive-connector-3.1-0.5-20230519.001932-15.jar

### Compute Engine

hive-3.1.0

### Minimal reproduce step

0: jdbc:hive2://ambari.bi.lyf.test:2181,nn01.> select id,order_no,create_time from ods.zt_tc_order_paimon a;
INFO  : Compiling command(queryId=hive_20230522165519_4501567f-83d4-40ae-b6a1-5cc8c2f1a6f9): select id,order_no,create_time from ods.zt_tc_order_paimon a
INFO  : Semantic Analysis Completed (retrial = false)
INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:id, type:bigint, comment:null), FieldSchema(name:order_no, type:string, comment:null), FieldSchema(name:create_time, type:timestamp, comment:null)], properties:null)
INFO  : Completed compiling command(queryId=hive_20230522165519_4501567f-83d4-40ae-b6a1-5cc8c2f1a6f9); Time taken: 0.325 seconds
INFO  : Executing command(queryId=hive_20230522165519_4501567f-83d4-40ae-b6a1-5cc8c2f1a6f9): select id,order_no,create_time from ods.zt_tc_order_paimon a
INFO  : Completed executing command(queryId=hive_20230522165519_4501567f-83d4-40ae-b6a1-5cc8c2f1a6f9); Time taken: 0.25 seconds
INFO  : OK
java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
	at java.sql.Timestamp.valueOf(Timestamp.java:237)
	at org.apache.hive.jdbc.HiveBaseResultSet.evaluate(HiveBaseResultSet.java:445)
	at org.apache.hive.jdbc.HiveBaseResultSet.getColumnValue(HiveBaseResultSet.java:425)
	at org.apache.hive.jdbc.HiveBaseResultSet.getObject(HiveBaseResultSet.java:467)
	at org.apache.hive.beeline.Rows$Row.<init>(Rows.java:160)
	at org.apache.hive.beeline.BufferedRows.<init>(BufferedRows.java:57)
	at org.apache.hive.beeline.IncrementalRowsWithNormalization.<init>(IncrementalRowsWithNormalization.java:50)
	at org.apache.hive.beeline.BeeLine.print(BeeLine.java:2305)
	at org.apache.hive.beeline.Commands.executeInternal(Commands.java:1026)
	at org.apache.hive.beeline.Commands.execute(Commands.java:1201)
	at org.apache.hive.beeline.Commands.sql(Commands.java:1130)
	at org.apache.hive.beeline.BeeLine.dispatch(BeeLine.java:1480)
	at org.apache.hive.beeline.BeeLine.execute(BeeLine.java:1342)
	at org.apache.hive.beeline.BeeLine.begin(BeeLine.java:1126)
	at org.apache.hive.beeline.BeeLine.mainWithInputRedirection(BeeLine.java:546)
	at org.apache.hive.beeline.BeeLine.main(BeeLine.java:528)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:232)
Error: Unrecognized column type:TIMESTAMP_TYPE (state=,code=0)
0: jdbc:hive2://ambari.bi.lyf.test:2181,nn01.>

### What doesn't meet your expectations?

timestamp format error

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
@Deeservent Did you use the paimon table created by hive? ddl?

**Comment by Deeservent** [comment]
@zhuangchong created by Flink SQL client,

Here is the complete ddl!

create table paimon.ods.zt_tc_order_paimon(
id                        bigint        comment '',
seller_id                 bigint        comment '',
buyer_id                  bigint        comment '',
order_no                  string        comment '',
parent_order_no           string        comment '',
order_no_out              string        comment '',
trade_type                int           comment '',
trade_status              int           comment '',
channel                   string        comment '',
source                    int           comment '',
client                    string        comment '',
payment_time              timestamp     comment '',
amount                    decimal(18,2) comment '',
orgin_amount              decimal(18,2) comment '',
delivery_fee              decimal(18,2) comment '',
actual_amount             decimal(18,2) comment '',
discount_price            decimal(18,2) comment '',
device_id                 string        comment '',
is_reverse                int           comment '',
is_normal                 int           comment '',
operator_id               bigint        comment '',
expect_receive_type       int           comment '',
expect_receive_time       timestamp     comment '',
ext_data                  string        comment '',
create_time               timestamp     comment '',
update_time               timestamp     comment '',
creator                   string        comment '',
modifier                  string        comment '',
app_id                    string        comment '',
is_deleted                int           comment '',
version_no                int           comment '',
tenant_id                 string        comment '',
merchant_id               bigint        comment '',
channel_code              string        comment '',
shop_code                 string        comment '',
order_receive_time        timestamp     comment '',
order_logistics_time      timestamp     comment '',
is_parent                 int           comment '',
cancel_reason_desc        string        comment '',
cancel_type               int           comment '',
cancel_operate_id         bigint        comment '',
cancel_time               timestamp     comment '',
user_type                 string        comment '',
can_reverse               int           comment '',
delivery_type_code        string        comment '',
cancel_reason_id          int           comment '',
shop_type                 int           comment '',
is_pre_sale               int           comment '',
ext_param                 string        comment '',
is_show                   int           comment '',
expect_delivery_time      timestamp     comment '',
dt STRING,
PRIMARY KEY (dt,id) NOT ENFORCED
) PARTITIONED BY (dt)
with (
'bucket'='3',
'bucket-key'='id',
'file.format'='parquet',
'merge-engine'='partial-update',
'changelog-producer' = 'full-compaction', --指定 changelog producer 为 full-compaction
'changelog-producer.compaction-interval' = '1 min', --指定 campaction 的间隔为40秒
'snapshot.time-retained' = '3h',
'partial-update.ignore-delete'='true',
'full-compaction.delta-commits' ='10'
);

**Comment by Deeservent** [comment]
Tks!
