### ISSUE TITLE
[Bug] drop table in hive and then rebuild table error

### ISSUE THREAD

**Issue by yaowanli** [apache/incubator-paimon#1203]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5-SNAPSHOT

### Compute Engine

Flink-1.17.0;
Hive-3.1.0 ,Hive on Tez;

### Minimal reproduce step

1.In flink,create a table like :
CREATE CATALOG ods WITH (
'type' = 'paimon',
'metastore' = 'hive',
'uri' = 'thrift://IP:9083',
'warehouse' = 'hdfs://IP/warehouse/tablespace/managed/hive'
);
use catalog ods;
create table test1(
id bigint,
create_time string,
update_time string,
delete_flag int,
version int,
PRIMARY KEY (id) NOT ENFORCED
)
WITH (
'bucket' = '32',
'write-mode' = 'change-log',
'snapshot.time-retained' = '1h'
);
2.And then ,drop table in Hive,like:
drop table test1;
Hive will return "Updated Rows:-1"
3.After that,create the same table in Flink,like step 1, Flink will throw Exception,and can't create the same table .

### What doesn't meet your expectations?

[ERROR] Could not execute SQL statement. Reason:
java.lang.IllegalStateException: Schema in filesystem exists, please use updating, latest schema is: Optional[{
  "id" : 0,
  "fields" : [ {
    "id" : 0,
    "name" : "id",
    "type" : "BIGINT NOT NULL"
  }, {
    "id" : 1,
    "name" : "create_time",
    "type" : "STRING"
  }, {
    "id" : 2,
    "name" : "update_time",
    "type" : "STRING"
  }, {
    "id" : 3,
    "name" : "delete_flag",
    "type" : "INT"
  }, {
    "id" : 4,
    "name" : "version",
    "type" : "INT"
  } ],
  "highestFieldId" : 4,
  "partitionKeys" : [ ],
  "primaryKeys" : [ "id" ],
  "options" : {
    "bucket" : "32",
    "write-mode" : "change-log",
    "snapshot.time-retained" : "1h"
  }
}]

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
Can you assign it to me?

**Comment by zhuangchong** [comment]
@yaowanli 
I tested to create a table in flink, drop this table in hive, it can be deleted normally, can you confirm whether there is any exception log when you use hive to drop the table?

**Comment by zhuangchong** [comment]
I will close this issue first. If you still have questions, you can open this issue again.
