### ISSUE TITLE
HdfsFileSizeLimitation_Not_effective

### ISSUE THREAD

**Issue by wangyayuan18** [apache/incubator-paimon#1210]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

![image](https://github.com/apache/incubator-paimon/assets/64136230/c89586d2-6fcf-4514-9d22-0ed7be71a85f)
Flink1.16Version——IcebergData BatchProcessing in Paimon

![image](https://github.com/apache/incubator-paimon/assets/64136230/054778db-78a5-4def-bbb0-93c622daa531)
Flink1.17Version——Add Limit file size parameter
![image](https://github.com/apache/incubator-paimon/assets/64136230/2aa4e765-b630-48c7-ab99-d5a26c17f96c)

### Compute Engine

Flink

### Minimal reproduce step

After adding the file size limit parameter，The data file still exceeds 128mb。
![image](https://github.com/apache/incubator-paimon/assets/64136230/8f10c8aa-ecce-4245-95d7-bb07e453a853)

![image](https://github.com/apache/incubator-paimon/assets/64136230/4a7e3fa6-f2b5-4da9-9b7e-ad7659d3d333)

### What doesn't meet your expectations?

Because the block size set by my HDFS is 128mb，If it exceeds 128mb, hdfs query data is not disk friendly, so the maximum file size should not exceed 128mb。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liming30** [comment]
Thanks @wangyayuan18  for reporting.
Could you please confirm the average size of a single record first?  `targetFileSize` is just a suggested value, not a hard limit. Currently, we check whether the file size exceeds `targetFileSize` every time we write 1000 records. If the average size of records is relatively large, the file will exceed `targetFileSize`.

**Comment by wangyayuan18** [comment]
> Thanks @wangyayuan18 for reporting.
> 
> Could you please confirm the average size of a single record first? `targetFileSize` is just a suggested value, not a hard limit. Currently, we check whether the file size exceeds `targetFileSize` every time we write 1000 records. If the average size of records is relatively large, the file will exceed `targetFileSize`.

Write tens of thousands to 100000 entries per second on average

**Comment by JingsongLi** [comment]
The reason is that we don't consider the data in memory.

**Comment by wangyayuan18** [comment]
> Write tens of thousands to 100000 entries per second on average

![image](https://github.com/apache/incubator-paimon/assets/64136230/23f0cc9b-cdd3-4f6f-8052-7a631c7a460d)
Each bucket has a maximum file size of over 200MB, a minimum file size of kb, and several tens of mb
I want to limit the maximum file size to HDFS block size, my HDFS block size is 128mb

**Comment by wangyayuan18** [comment]
> Write tens of thousands to 100000 entries per second on average

![image](https://github.com/apache/incubator-paimon/assets/64136230/23f0cc9b-cdd3-4f6f-8052-7a631c7a460d)
Each bucket has a maximum file size of over 200MB, a minimum file size of kb, and several tens of mb
I want to limit the maximum file size to HDFS block size, my HDFS block size is 128mb

**Comment by liming30** [comment]
> The reason is that we don't consider the data in memory.

@JingsongLi Please assign it to me.

**Comment by JingsongLi** [comment]
thanks @liming30
