### ISSUE TITLE
[Bug][Doc] The snapshot3 image in file operation might contain a typo

### ISSUE THREAD

**Issue by JingGe** [apache/incubator-paimon#1219]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

https://github.com/JingGe/incubator-paimon/commit/e1dd82d9a430fda322eca771f3f14e0d1646aa01

### Compute Engine

Flink

### Minimal reproduce step

https://github.com/JingGe/incubator-paimon/blob/master/docs/static/img/file-operations-2.png

### What doesn't meet your expectations?

It should be a typo, if I am not mistaken. The last data file is created for partition `20230503` to 20230510 just like file-operations-3.png did. In file-operations-2.png it is still `20230502` to 20230510

I wanted to submit a PR, but unfortunately there is no source of the image.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by qidian99** [comment]
Image source send via pm. please check.
