### ISSUE TITLE
[Feature] Batch Table Without Bucket

### ISSUE THREAD

**Issue by leaves12138** [apache/incubator-paimon#1224]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently, paimon has very high support for stream write and stream read, but not enough for traditional batch processing. After the table is created, you need to display the specified bucket key and bucket number; otherwise, the AppendOnly table or changelog table for a single bucket is created. When there is only one bucket, concurrent read/write and compact cannot be performed, resulting in poor batch performance.

see https://cwiki.apache.org/confluence/display/PAIMON/PIP-6%3A+Batch+Table+Without+Bucket

### Solution

see https://cwiki.apache.org/confluence/display/PAIMON/PIP-6%3A+Batch+Table+Without+Bucket

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
The related PR has been merged and I will close this issue.
