### ISSUE TITLE
Field cannot be deleted

### ISSUE THREAD

**Issue by wangyayuan18** [apache/incubator-paimon#1231]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

[paimon-flink-1.17-0.5-SNAPSHOT.jar](https://repository.apache.org/snapshots/org/apache/paimon/paimon-flink-1.17/0.5-SNAPSHOT/)

### Compute Engine

Flink SQL CLI Client

### Minimal reproduce step

Start by adding the unknown field

ALTER TABLE my_table ADD unknown STRING AFTER mt;

mt field is my partition field

Problems that arise
![image](https://github.com/apache/incubator-paimon/assets/64136230/b26fcd93-068d-48f2-99a0-12d8eb1a67fa)

### What doesn't meet your expectations?

Field cannot be deleted

![image](https://github.com/apache/incubator-paimon/assets/64136230/6bff9374-4c55-4da6-b937-753e72ac17b1)

![image](https://github.com/apache/incubator-paimon/assets/64136230/071406ee-e3b5-4451-9642-e03dcea1ba39)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhangjun0x01** [comment]
I try it in my computer,it is ok .
could you provide  more information？


```
Flink SQL> 
> CREATE CATALOG paimon_hive_catalog WITH (
>      'type' = 'paimon',
>     'metastore' = 'hive',
>     'table.type' = 'external',
>     'uri' = 'thrift://localhost:9083',
>     'warehouse' = 'hdfs://localhost/user/hive/warehouse'
> );
[INFO] Execute statement succeed.

Flink SQL> use catalog paimon_hive_catalog;
[INFO] Execute statement succeed.

Flink SQL> use zhangjun;
[INFO] Execute statement succeed.

Flink SQL> drop table mytable;
[INFO] Execute statement succeed.

Flink SQL> CREATE TABLE mytable (
>     user_id BIGINT,
>     item_id BIGINT,
>     behavior STRING,
>     dt STRING,
>     hh STRING,
>     PRIMARY KEY (dt, hh, user_id) NOT ENFORCED
> ) PARTITIONED BY (dt, hh);
[INFO] Execute statement succeed.

Flink SQL> alter table mytable add aaa string after dt;
[INFO] Execute statement succeed.

Flink SQL> desc mytable;
+----------+--------+-------+----------------------+--------+-----------+
|     name |   type |  null |                  key | extras | watermark |
+----------+--------+-------+----------------------+--------+-----------+
|  user_id | BIGINT | FALSE | PRI(dt, hh, user_id) |        |           |
|  item_id | BIGINT |  TRUE |                      |        |           |
| behavior | STRING |  TRUE |                      |        |           |
|       dt | STRING | FALSE | PRI(dt, hh, user_id) |        |           |
|      aaa | STRING |  TRUE |                      |        |           |
|       hh | STRING | FALSE | PRI(dt, hh, user_id) |        |           |
+----------+--------+-------+----------------------+--------+-----------+
6 rows in set

Flink SQL> alter table mytable drop (aaa);
[INFO] Execute statement succeed.

Flink SQL> 
```

**Comment by JingsongLi** [comment]
What is your hive metastore version?

**Comment by zhuangchong** [comment]
set hive.metastore.disallow.incompatible.col.type.changes false in hive-site.xml, and restart hive. See [HIVE-17832](https://issues.apache.org/jira/browse/HIVE-17832).

At the same time, I have added the test case of alter table when flink sql uses hive catalog.
