### ISSUE TITLE
[Feature] Add docs about managed memory in flink.md

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#1255]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Add docs about #796 

Subtask of #796 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by q977734161** [comment]
I am willing to try this ticket, counld you assign it to me！

**Comment by FangYongs** [comment]
Thanks @q977734161 , assigned
