### ISSUE TITLE
[Bug] [hive] Field Chinese comments cannot be displayed normally when using hive to query table metadata

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-paimon#1262]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5-SNAPSHOT

### Compute Engine

hive

### Minimal reproduce step

1. Flink SQL uses hive metastore to create catalog.

2.Flink SQL creates a table with Chinese comments.

3.Hive SQL query this table `desc formatted table_name`

### What doesn't meet your expectations?

Field Chinese comments cannot be displayed normally when using hive to query table metadata

![image](https://github.com/apache/incubator-paimon/assets/37063904/4098a49b-022c-494a-bc2a-6b3033baa42c)

![image](https://github.com/apache/incubator-paimon/assets/37063904/97fc6dcb-7ce7-49e9-b4e6-94849ca5992e)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Maybe the only way is converting unicode to string in `FlinkCatalog`?

**Comment by JingsongLi** [comment]
Does Spark also see unicode when using `FileSystemCatalog`?

**Comment by zhuangchong** [comment]
> Does Spark also see unicode when using `FileSystemCatalog`?

The same issue exists when spark reads the paimon table created by flink.

![image](https://github.com/apache/incubator-paimon/assets/37063904/eefb2517-7e79-4ea8-a79f-8723776833d7)

**Comment by zhuangchong** [comment]
Linked Flink issue: https://issues.apache.org/jira/browse/FLINK-32249
