### ISSUE TITLE
[Feature] Kafka Synchronizing Table Support Debezium, Maxwell, OGG Format

### ISSUE THREAD

**Issue by hiliuxg** [apache/incubator-paimon#1284]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Kafka Synchronizing Table Support Debezium, Maxwell, OGG Format

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jjrrzxc** [comment]
hi,i am willing to implements maxwell format because my company use maxwell as the base cdc ingestor。 so what can i do next before write and contribute code (i am a newcomer in open source projects)

**Comment by zhuangchong** [comment]
Already supported.

see https://paimon.apache.org/docs/master/cdc-ingestion/kafka-cdc/#supported-formats
