### ISSUE TITLE
[Feature] mysql cdc ingestion: Scan Newly Added Tables

### ISSUE THREAD

**Issue by www2388258980** [apache/incubator-paimon#1342]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

[# mysql cdc 2.3](https://ververica.github.io/flink-cdc-connectors/release-2.3/content/connectors/mysql-cdc.html)
Scan Newly Added Tables feature enables you add new tables to monitor for existing running pipeline, the newly added tables will read theirs snapshot data firstly and then read their changelog automatically.

Imaging this scenario: At the beginning, a Flink job monitor tables [product, user, address], but after some days we would like the job can also monitor tables [order, custom] which contains history data, and we need the job can still reuse existing state of the job, this feature can resolve this case gracefully.

by testing,i found mysql cdc ingestion don't back the feature.
```
[1]
/home/hadoop/flink-1.16.0/bin/flink run --detached \
/home/hadoop/flink-1.16.0/tools/paimon-flink-action-0.5-20230605.002307-17.jar \
mysql-sync-database \
......
......
......
--including-tables 'product|user|address'


[2]
/home/hadoop/flink-1.16.0/bin/flink run --detached \
--fromSavepoint hdfs:///tmp/savepoint/savepoint-3fece5-c82648407e14 \
--allowNonRestoredState \
/home/hadoop/flink-1.16.0/tools/paimon-flink-action-0.5-20230605.002307-17.jar \
mysql-sync-database \
......
......
......
--including-tables 'product|user|address|order|custom'
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
This is a high priority task

**Comment by qidian99** [comment]
Sounds like a legit scenario where user stops the sync job and restarts using new configuration to sync more tables.
