### ISSUE TITLE
[Bug][docs] cdc-ingestion.md fails to build

### ISSUE THREAD

**Issue by tsreaper** [apache/incubator-paimon#1356]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master (39f5c8c53254e581be2877c66dbea5709fe17b94)

### Compute Engine

Irrelevant.

### Minimal reproduce step

Run `hugo serve` in `docs` directory.

### What doesn't meet your expectations?

Hugo fails with

```
Error: Error building site: "/Users/tsreaper/github/incubator-paimon/docs/content/how-to/cdc-ingestion.md:179:21": failed to extract shortcode: template for shortcode "savepointPath" not found
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this
