### ISSUE TITLE
[Feature] Batch mode enable write-buffer-spillable by default

### ISSUE THREAD

**Issue by leaves12138** [apache/incubator-paimon#1369]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Write-buffer-spillable will cache the write and compaction files in local. At the time of finishing the job, push all the files to the remote filesystem at once.
So it could reduce network traffic and speed up writing.

In batch mode, it's better to enable this mode by default. 

### Solution

Enable write-buffer-spillable in batch mode by default.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by hililiwei** [comment]
May i have a try?

**Comment by leaves12138** [comment]
I have already done this, maybe found another issue?

**Comment by hililiwei** [comment]
> I have already done this, maybe found another issue?

Got it. Thx.
