### ISSUE TITLE
[Feature] Optimize memory for big column

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#1375]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently Paimon has some problems with memory usage if there is a column with a very large field, more than 2MB.

Problem:

1. Batch size (read.batch-size) not work for sink, currently, Orc writer also create a ColumnarBatch, we should limit its memory too.
2. Orc Dictionary needs much memory, we can introduce a common option and document this to close Dictionary.
3. In the scenario of frequent failover, we should restrict the continuation of new file committing, see #1351 
4. `RollingFileWriter` should not refer all writers, or we should set writer and maxKey to null in `SingleFileWriter`s.
5. We should avoid adding statistics to very large columns, which can cause our Manifest file to become very large.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wg1026688210** [comment]
I'm willing to submit a PR!

**Comment by zhangjun0x01** [comment]
hi,@JingsongLi , do you think is it necessary to separate key and value  for big value? like this : https://rocksdb.org/blog/2021/05/26/integrated-blob-db.html

**Comment by JingsongLi** [comment]
> hi,@JingsongLi , do you think is it necessary to separate key and value for big value? like this : https://rocksdb.org/blog/2021/05/26/integrated-blob-db.html

This is a huge topic....

**Comment by zhangjun0x01** [comment]
> > hi,@JingsongLi , do you think is it necessary to separate key and value for big value? like this : https://rocksdb.org/blog/2021/05/26/integrated-blob-db.html
> 
> This is a huge topic....

Doris also has similar function, and I think paimon currently may does not have strong user needs. We can discuss this topic when users have needs later.

**Comment by JingsongLi** [comment]
> Doris also has similar function, and I think paimon currently may does not have strong user needs. We can discuss this topic when users have needs later.

Hi @zhangjun0x01 , if just for performance improvement, yes Paimon also has the requirement. Can you just create a new issue?

**Comment by zhangjun0x01** [comment]
> > Doris also has similar function, and I think paimon currently may does not have strong user needs. We can discuss this topic when users have needs later.
> 
> Hi @zhangjun0x01 , if just for performance improvement, yes Paimon also has the requirement. Can you just create a new issue?

I create a new issue https://github.com/apache/incubator-paimon/issues/1428
