### ISSUE TITLE
[Feature] Method hasNext blocks the iterator when the data is not arrived

### ISSUE THREAD

**Issue by yuzyf** [apache/incubator-paimon#1377]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

        TableResult tableResult = tenv.executeSql("SELECT project__id,dept__id FROM paimon_catalog.test.production_plan_development WHERE plan_id = '" + planId + "' AND version = " + version);
        CloseableIterator<Row> iterator = tableResult.collect();
        if (iterator.hasNext()) {}
现在这段代码查不到数据的话、就会在iterator.hasNext()进行阻塞、有数据就不会阻塞、我的理解是hasNext、没有数据不应该返回false直接跳过吗、现在有什么可以修改的方案吗、谢谢

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
@yuzyf This is a Flink issue, you are using streaming mode, so the iterator will be blocked to wait next record.

You should use batch mode...

**Comment by JingsongLi** [comment]
And please use English in github issue.

**Comment by yuzyf** [comment]
> @yuzyf This is a Flink issue, you are using streaming mode, so the iterator will be blocked to wait next record.
> 
> You should use batch mode...

I have set in my code
<img width="933" alt="image" src="https://github.com/apache/incubator-paimon/assets/77232395/967ed240-cd51-4690-b2df-0916ee542c57">

**Comment by JingsongLi** [comment]
@yuzyf If you are using batch mode, you can launch a thread to iterate records.

**Comment by FangYongs** [comment]
I think the method `hasNext` blocks the iterator is a valid action when no data has arrived. If a iterator returns false in `hasNext()`, it means the iterator has no more data. The execution of job is asynchronous, no data at the moment does means the iterator has no more data.
