### ISSUE TITLE
[Feature][cdc] Add option to decide whether tinyint(1) should be converted to bool or byte

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#1395]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Now, we convert tinyint(1) to bool by default. This is a common behavior.

But sometimes we need a byte to store more values. We can introduce an option to CDC.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by legendtkl** [comment]
Hi, @JingsongLi , I would like to take this ticket, thanks.

**Comment by legendtkl** [comment]
Hi, @JingsongLi , this is implementation proposal:

Add a table conf `convert-tinyint-byte` in Action, such as
```bash
<FLINK_HOME>/bin/flink run \
    /path/to/paimon-flink-action-0.5-SNAPSHOT.jar \
    mysql-sync-table \
    --warehouse hdfs:///path/to/warehouse \
    --database test_db \
    --table test_table \
    --partition-keys pt \
    --primary-keys pt,uid \
    --computed-columns '_year=year(age)' \
    --mysql-conf hostname=127.0.0.1 \
    --mysql-conf username=root \
    --mysql-conf password=123456 \
    --mysql-conf database-name=source_db \
    --mysql-conf table-name='source_table_.*' \
    --catalog-conf metastore=hive \
    --catalog-conf uri=thrift://hive-metastore:9083 \
    --table-conf bucket=4 \
    --table-conf changelog-producer=input \
    --table-conf sink.parallelism=4 \
   --table-conf convert-tinyint-byte=true
```

Then we pass the config into `MySqlTypeUtils#toDataType()` method for handling `TINYINT` type.
