### ISSUE TITLE
 expectation as a new requirement

### ISSUE THREAD

**Issue by Aload** [apache/incubator-paimon#1397]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Demand scenario:

There is a source table of dwd layer, the main function is to use the primary key to de-duplicate, and the sequence-field is used to get the latest one. However, with a table of dws, I need to subscribe/stream read the table of dwd layer, so that it can get the latest one every time. At present, I refer to the changelog-producer. scan-mode, I have communicated with Mr.song and confirmed that it is a new requirement.

### Solution

NONE

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
The current default behavior is that there will be de-duplication within the checkpoint.

If you configure changelog-producer=full-compaction, it will de-duplicate more, depending on your latency requirements.
