### ISSUE TITLE
[Feature] HiveCatalog should support case sensitive names for Hive3

### ISSUE THREAD

**Issue by yuzelin** [apache/incubator-paimon#1398]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Hive 3 is case sensitive.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Maybe Hive 3 also case insensitive too...

**Comment by yuzelin** [comment]
> Maybe Hive 3 also case insensitive too...

Right. Closed.
