### ISSUE TITLE
[Feature] Add docs of managing and reading tag

### ISSUE THREAD

**Issue by yuzelin** [apache/incubator-paimon#1406]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

We have introduced tag. We should add docs for it.
Sub task of #1269 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by MonsterChenzhuo** [comment]
@yuzelin  please assign to me; thx。

**Comment by yuzelin** [comment]
@MonsterChenzhuo Sorry for late response. I'm working on this now.
