### ISSUE TITLE
[Bug] MySQL CDC may throw error when handling TINYINT(1)

### ISSUE THREAD

**Issue by yuzelin** [apache/incubator-paimon#1420]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

flink

### Minimal reproduce step

MySQL TINYINT(1) ;
insert 21.

### What doesn't meet your expectations?

Current implementation use bool to transfer TINYINT(1), which may cause error.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by legendtkl** [comment]
hi, @yuzelin , I would like to take this issue, would you help assign it to me?

Thanks.

**Comment by john8628** [comment]
same with https://github.com/apache/incubator-paimon/issues/1395;

**Comment by yuzelin** [comment]
Thanks, @john8628 , I will close this.
cc @legendtkl
