### ISSUE TITLE
[Feature] Support MySQL TIME types when using HiveCatalog in CDC

### ISSUE THREAD

**Issue by yuzelin** [apache/incubator-paimon#1421]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently, Hive doesn't support TIME type.  So if MySQL table has TIME field, and set Paimon catalog to HiveCatalog, it will throw error.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
#1813
