### ISSUE TITLE
[Feature] 多表合并sink写入

### ISSUE THREAD

**Issue by melin** [apache/incubator-paimon#1444]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

如果大量表同步（三位数量表），每一个表一个sink，flink cdc 非常耗资源，基本不可用。paimon 能否支持？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
There is PR to support this: https://github.com/apache/incubator-paimon/pull/1261

And please use chianese.

**Comment by qidian99** [comment]
#1261 this PR may alleviate the performance issue. IMHO, Flink is now well suited for syncing over a hundred tables. 

Let's say you have 100 tables and 16 buckets for each table. Suppose the optimal parallelism is 8, and that will still cause 1 slot to maintain 100 * 16 / 8 = 200 file handles on average. If the average flush time for a file handle during checkpoint is 5s, then the pipeline will hang for 200 * 5s = 16min on each checkpoint. 

As far as Apache Hudi goes, there's no best practices for syncing > 100 tables using Hudi with bucket index. Paimon now don't have a benchmark on performance for different # of tables, but I believe it will outperform Hudi in syncing multiple tables.
