### ISSUE TITLE
[Feature] Implement IncrementalBetween table valued function in SparkSessionExtensions

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#1451]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently, incrementalBetween cannot be run through Spark SQL.

One way is to use TableValuedFunction, which requires us to extend SparkSessionExtensions.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by YannByron** [comment]
@JingsongLi I can take this.
