### ISSUE TITLE
[Feature] query the consumer id  of the table through consumer table

### ISSUE THREAD

**Issue by macdoor** [apache/incubator-paimon#1475]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

support such query
SELECT * FROM MyTable$consumer

### Solution

I want to query the consumer id  of the table through consumer table.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
Can it be assigned to me? 
I will add a new consumers system table for query, similar to the system table schemas.
