### ISSUE TITLE
[Feature] Add lineage meta related interfaces

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#1479]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Add lineage meta related interfaces, subtask of #684

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liming30** [comment]
I can work on this recently, please assign it to me.
