### ISSUE TITLE
[Feature] Support query for table lineage data

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#1482]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

subtask for #684 , query table lineage data for sql

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by legendtkl** [comment]
Hi, @FangYongs , I would like to take this if no one take it.

Thanks.

**Comment by liming30** [comment]
Hi, @legendtkl sorry, we are now working on this.
