### ISSUE TITLE
[Feature] Align snapshot and checkpoint in split enumerator and source

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#1486]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

subtask for #1105 , @liming30 I create this issue for alignment between split enumerator and source reader, please feel free to create subtask for it.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liming30** [comment]
@JingsongLi @FangYongs I have added related tests, please review it if you have time.
