### ISSUE TITLE
[Bug] file.compression do no work for parquet format

### ISSUE THREAD

**Issue by Aitozi** [apache/incubator-paimon#1494]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

parquet format

### Minimal reproduce step

<img width="882" alt="image" src="https://github.com/apache/incubator-paimon/assets/9486140/f8040d30-8b58-48be-8606-c898b6ba9345">

In parquet format, it will use `compress` key to extract from the option, and it has the higher preference than from the `file.compression`. So the actual work key is `compress`

### What doesn't meet your expectations?

the actual compression algorithm

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhangjun0x01** [comment]
I test it in my computer,it is ok, could you provide more information? 
```
Flink SQL> create table t6(id int , name string) with ('file.format'='parquet','file.compression'='ZSTD');
[INFO] Execute statement succeed.

Flink SQL> insert into t6 select 6,'bbb';
[INFO] Submitting SQL update statement to the cluster...
[INFO] SQL update statement has been successfully submitted to the cluster:
Job ID: 4a4712de0ecf72630ba801aad35702cf


Flink SQL> select * from t6;
+----+------+
| id | name |
+----+------+
|  6 |  bbb |
+----+------+
1 row in set

Flink SQL> 

```

**Comment by Aitozi** [comment]
Hi @zhangjun0x01 , have you verified that the `'file.compression'='ZSTD'` has actually worked ?

**Comment by Aitozi** [comment]
@zhangjun0x01  I just push a fix for this, could you help take a look ?

**Comment by JingsongLi** [comment]
@Aitozi This issue should be "parquet.compression not work"?

**Comment by Aitozi** [comment]
`parquet.compression` can work, `file.compression` not work. 
The option in [configuration](https://paimon.apache.org/docs/master/maintenance/configurations/) is `file.compression`. I think `parquet.compression` is not the recommended way now?
