### ISSUE TITLE
[Bug]  can not create table by java api with ROW data type

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/incubator-paimon#1530]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

no

### Minimal reproduce step

create table with  java api

```
        Schema.Builder schemaBuilder = Schema.newBuilder();
        schemaBuilder.column("f0", DataTypes.INT());
        schemaBuilder.column("f1", DataTypes.STRING());
        schemaBuilder.column("f2", DataTypes.ROW(DataTypes.STRING()));
        Schema schema = schemaBuilder.build();

        Identifier identifier = Identifier.create("test", "my_table1");
        try {
            catalog.createTable(identifier, schema, false);
        } catch (Catalog.TableAlreadyExistException e) {
            // do something
        } catch (Catalog.DatabaseNotExistException e) {
            // do something
        }

```

### What doesn't meet your expectations?

```
java.lang.RuntimeException: java.lang.RuntimeException: Broken schema, field id 0 is duplicated.

	at org.apache.paimon.catalog.FileSystemCatalog.uncheck(FileSystemCatalog.java:207)
	at org.apache.paimon.catalog.FileSystemCatalog.createTable(FileSystemCatalog.java:164)


```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
@zhangjun0x01 
I see you did not choose `I'm willing to submit a PR!`, can you assign this task to me?
I will modify the RowType class collectFieldIds method:

```
public void collectFieldIds(Set<Integer> fieldIds) {
        int index = -1;
        for (DataField field : fields) {
            if (fieldIds.contains(field.id())) {
                throw new RuntimeException(
                        String.format("Broken schema, field id %s is duplicated.", field.id()));
            }
            fieldIds.add(++index);
            Set<Integer> structuredFieldIds = new HashSet<>();
            field.type().collectFieldIds(structuredFieldIds);
            for (Integer ignored : structuredFieldIds) {
                fieldIds.add(++index);
            }
        }
    }
```

**Comment by zhangjun0x01** [comment]
> @zhangjun0x01 I see you did not choose `I'm willing to submit a PR!`, can you assign this task to me? I will modify the RowType class collectFieldIds method:
> 
> ```
> public void collectFieldIds(Set<Integer> fieldIds) {
>         int index = -1;
>         for (DataField field : fields) {
>             if (fieldIds.contains(field.id())) {
>                 throw new RuntimeException(
>                         String.format("Broken schema, field id %s is duplicated.", field.id()));
>             }
>             fieldIds.add(++index);
>             Set<Integer> structuredFieldIds = new HashSet<>();
>             field.type().collectFieldIds(structuredFieldIds);
>             for (Integer ignored : structuredFieldIds) {
>                 fieldIds.add(++index);
>             }
>         }
>     }
> ```

welcome， you can submit a PR directly
