### ISSUE TITLE
[Feature] Supports kafka log system registration

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#1533]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Kafka logsystem implements register interface, subtask of #1514 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by legendtkl** [comment]
Hi, @FangYongs , I would like to take this, would you help assign it to me?

Thanks.
