### ISSUE TITLE
[Feature] Introduce file clean action

### ISSUE THREAD

**Issue by yuzelin** [apache/incubator-paimon#1571]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently, the `FileStoreExpireImpl` delete file quietly, which means if there occurs error, the process won't throw exceptions. It's possible that some files won't be deleted when snapshot expiring, so I propose to introduce an action to clean files unused by current snapshots. 

### Solution

Scan all files and filter out that still used by at least one snapshot, then delete those not used by any snapshot.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by john8628** [comment]
can I have a try?

**Comment by yuzelin** [comment]
> can I have a try?

Hi, john, thanks. Surely you can just push some commits.

**Comment by john8628** [comment]
> > can I have a try?
> 
> Hi, @john8628, thanks. Surely you can just push some commits.

thanks. I will give some implements using Flink action . The steps will be:
1. Perform an initial scan of all the data files ,  A.
2. Obtain the files for all snapshots files  ,  B.
3. Calculate the set difference A - B to find new files.

**Comment by JingsongLi** [comment]
@john8628 You can just create a PR.

**Comment by john8628** [comment]
Apologies, I am unable to continue working on this PR due to other commitments,and I will need to close this pull request for now as the work is incomplete.  @john8628 @JingsongLi
