### ISSUE TITLE
[Feature] Support Reset next snapshot id of consumer id

### ISSUE THREAD

**Issue by ChenShuai1981** [apache/incubator-paimon#1574]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently paimon does NOT support reset next snapshot id of consumer id which is not convenient in `DATA FIXING` scenario

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
Can this task be assigned to me?

I will create a `reset consumer` action for reset next snapshot id of consumer id.
