### ISSUE TITLE
[Feature] Spark supports PARTITION MANAGEMENT

### ISSUE THREAD

**Issue by YannByron** [apache/incubator-paimon#1584]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Spark supports PARTITION MANAGEMENT.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by choucmei** [comment]
Through implements SupportsPartitionManagement interface to support this feature.
I want to implement  this feature
