### ISSUE TITLE
[Feature] kafka cdc support maxwell output json format

### ISSUE THREAD

**Issue by leaves12138** [apache/incubator-paimon#1591]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Now paimon only support canal-json format sync to paimon by flink cdc. We need to add a formatter to decode the json comes from maxwell.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by john8628** [comment]
can you assign it to me  ,i'd like to work for it

**Comment by zhuangchong** [comment]
Related #1963
