### ISSUE TITLE
[Feature] Support Global System Table which record metadata of all paimon tables

### ISSUE THREAD

**Issue by ChenShuai1981** [apache/incubator-paimon#1612]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

There are so many paimon tables, and I want to find which paimon tables has 'write-only' = 'true' option. 
Currently there is NO system tables provided by paimon, but only T$options system table companion with paimon table. 
It is hard for me to get all those write-only paimon tables because I have to iterate all paimon table names, and query its companion T$options system table, then check those options one by one.
If paimon support Global system table just like information_schema.tables in mysql, I can query them quickly by fire the following sql:

`select table_name from paimon_catalog.information_schema.tables where option_key = 'write-only' and option_value = 'true'`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
the related pr: #1647

The related PR has been merged, you are welcome to try this feature, I will close this issue.
