### ISSUE TITLE
[Feature] Support T$partitions system table which store partition related information

### ISSUE THREAD

**Issue by ChenShuai1981** [apache/incubator-paimon#1633]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently, there is no system table in paimon which store partition related information. Especially in partition expiration scenario, those expired partitions are logically deleted without delete partition folder physically. User does NOT know which partitions are retained and can be queried. 
By supporting T$partitions system table, user can fire the following sql to query them out: `select * from T$partitions`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
https://iceberg.apache.org/docs/latest/spark-queries/#partitions

**Comment by john8628** [comment]
could you assign it  to me , i will try this ;
