### ISSUE TITLE
[Bug] FlinkCdcSyncDatabaseSinkITCase. testRandomCdcEventsDynamicBucket is not stable

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#1645]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

Error:  Errors: 
Error:    FlinkCdcSyncDatabaseSinkITCase.testRandomCdcEventsDynamicBucket » Timeout test...

https://github.com/apache/incubator-paimon/actions/runs/5652244000/job/15311564241?pr=1603

### Compute Engine

flink cdc

### Minimal reproduce step

ci failed

### What doesn't meet your expectations?

ci failed

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liming30** [comment]
The main reason is that [numRecordsPerCheckpoint](https://github.com/apache/incubator-paimon/blob/master/paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcSourceFunction.java#L55) may be 0, which makes [TestCdcSourceFunction](https://github.com/apache/incubator-paimon/blob/master/paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/sink/cdc/TestCdcSourceFunction.java#L83) unable to send data. I have created a pr, if you have time, please help to review it.
