### ISSUE TITLE
[Feature] the system table of snapshot need add watermark field.

### ISSUE THREAD

**Issue by wg1026688210** [apache/incubator-paimon#1654]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

In the documentation of systerm-tables, the snapshot table does not display the watermark field. We need to add it.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liming30** [comment]
@wg1026688210 Is anyone else working on this? If not, I would like to do this.

**Comment by wg1026688210** [comment]
> @wg1026688210 Is anyone else working on this? If not, I would like to do this.
ok,I have not worked on this
