### ISSUE TITLE
[Bug] flink cdc database sync will throw an exception when drop table 

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/incubator-paimon#1700]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master 

### Compute Engine

flink
k8s

### Minimal reproduce step

1. start a flink job to sync mysql database to paimon
2. drop a mysql table
3. it throw an exception 
```
Invalid historyRecord, because tableChanges should contain exactly 1 item
```

### What doesn't meet your expectations?

the message is like this:

```
{
    "source":{
        "file":"mysql-bin.000040",
        "pos":2266343,
        "server_id":1
    },
    "position":{
        "transaction_id":null,
        "ts_sec":1690875697,
        "file":"mysql-bin.000040",
        "pos":2266468,
        "server_id":1
    },
    "databaseName":"db1",
    "ddl":"DROP TABLE `db1`.`t4`",
    "tableChanges":[

    ]
}
```

The program will throw an exception and be blocked , the  subsequent operations cannot be synchronized

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
Solved by #1702
