### ISSUE TITLE
Support for Non-Merging of Identical Table Names in Multi-Database Synchronization using MySQL CDC

### ISSUE THREAD

**Issue by newsuperchao** [apache/incubator-paimon#1706]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

In actual business scenarios, there exist tables with the same name in different databases, but the table structures are different. If these are merged, it will cause errors. Or for certain business requirements, merging tables with the same name is not allowed.

### Solution

I hope that the merging of the same tables can be configurable. For example, add a parameter. If not merged, use the $dbName_$tableName method by default.

Thank you for considering this feature request. I look forward to your response.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
Resolved by #1721
