### ISSUE TITLE
[Bug] flink cdc sync can not support `BIT(n)` data type

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/incubator-paimon#1707]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

flink

### Minimal reproduce step

1. start a flink sync job to sync mysql table to paimon
2. the mysql table has `bit` and `bit(10)` type
3. now all the mysql `bit` data type be converted to paimon `BOOLEAN` .
4. if the mysql  data of the `BIT(10)` type is `B'0000111'` , it can not be converted to paimon `BOOLEAN`. 

### What doesn't meet your expectations?

it will throws an exception.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
This PR is done and I will close this issue.
