### ISSUE TITLE
[Bug] can not sync multiple table with regular expression in flink sync table action

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/incubator-paimon#1711]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master 

### Compute Engine

flink

### Minimal reproduce step

1. start a flink mysql table action to sync multiple with regular with regular expression ,
    like `    --mysql-conf table-name='source_table1|source_table2'  `
2. the first table `source_table1` can be synchronized to paimon, and the second  table `source_table2 ` can not be synchronized.

### What doesn't meet your expectations?

the second table  can not be synchronized.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Paper-plane123** [comment]
Is the structure of the two tables the same?
Synchronizing Tables:
By using [MySqlSyncTableAction] in a Flink DataStream job or directly through flink run, users can synchronize one or multiple tables from MySQL into one Paimon table.

**Comment by zhangjun0x01** [comment]
> Is the structure of the two tables the same? Synchronizing Tables: By using [MySqlSyncTableAction] in a Flink DataStream job or directly through flink run, users can synchronize one or multiple tables from MySQL into one Paimon table.

the schema of the two tables are same

**Comment by Paper-plane123** [comment]
Which version of the 'flink-connector-mysql-cdc' package did you use?

**Comment by Paper-plane123** [comment]
The 'flink-connector-mysql-cdc' package for the 'table-name 'parameter is handled differently in versions 2.4 and 2.3(Paimon default). However, Paimon master branch concatenates the database name and the value of the 'table-name' parameter(MySqlSyncTableAction:138), you can try it in your environment by modifying the source code. 
I'm not sure if the problem is here, you need to judge combine your environment.

**Comment by zhangjun0x01** [comment]
> The 'flink-connector-mysql-cdc' package for the 'table-name 'parameter is handled differently in versions 2.4 and 2.3(Paimon default). However, Paimon master branch concatenates the database name and the value of the 'table-name' parameter(MySqlSyncTableAction:138), you can try it in your environment by modifying the source code. I'm not sure if the problem is here, you need to judge combine your environment.

The fundamental reason is that this `tableList`, (https://github.com/apache/incubator-paimon/blob/4bf77f18377d4783868723d897eb4ffce44bb1d1/paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java#L138)

Assuming we have a database `db1` , and the `table-name='source_table1|source_table2'` ,the `tableList` will be `db1.source_table1|source_table2` , but the correct format should be  `db1.source_table1|db1.source_table2`

**Comment by Paper-plane123** [comment]
You can have a try by set the 'table-name = source_table1|db1.source_table2'.

**Comment by yuzelin** [comment]
Yes, the 'tableList' is incorrect in this scenario, we should build the table list like `(db_pattern)\\.(table_pattern)`
