### ISSUE TITLE
[Feature] Add option to disable ddl in default database

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#1729]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

If users don't create a database and create table directly, they will create all tables in the default database. From the perspective of permission control, we hope that each business can manage their tables based on the database. So we need to disable the ddl operation of the default database and force users to place their tables in the specified database

### Solution

Add an option to disable ddl in default database

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by legendtkl** [comment]
hi, @FangYongs , I would like to take this. Would you help assign it to me, thanks.
