### ISSUE TITLE
[Bug] FilesTable gets maxKey logic error in DataFileMeta

### ISSUE THREAD

**Issue by Asura7969** [apache/incubator-paimon#1755]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5-snapshot

### Compute Engine

flink

### Minimal reproduce step

The verification field is inconsistent with the actual obtained field

### What doesn't meet your expectations?

![image](https://github.com/apache/incubator-paimon/assets/26200914/5c43b4fc-0d6b-4d6f-b003-12b96ea83a8d)

### Anything else?

No response

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
done.
