### ISSUE TITLE
[Bug] The priority of options in table should be higher than the default table options in catalog

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#1763]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently the default table options in catalog will override the options in table, the priorities for them are wrong

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by legendtkl** [comment]
hi, @FangYongs , I implemented the previous related logic, would you assign this to me?

Thanks.

**Comment by legendtkl** [comment]
After reviewing the code, the table options have higher priority than default options. 

Let's close the issue. cc @FangYongs
