### ISSUE TITLE
[Feature] Support statistics currentEmitEventTimeLag metrics

### ISSUE THREAD

**Issue by Tan-JiaLiang** [apache/incubator-paimon#1766]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

In the scenario of stream processing, there are two important metrics, one is the data processing delay and the other is the data stream interruption. Currently, the source of Flink's FLIP-33 supports the statistics of these two metrics, which correspond to currentEmitEventTimeLag (data processing delay) and sourceIdleTime (the time of the stream interruption).

### Solution

Among them, sourceIdleTime is already supported by default, but currentEmitEventTimeLag requires setting a record timestamp when emitting from source, which can refer to the design of flink-connector-kafka, it emit the kafka record timestamp from source. Therefore, if Paimon wants to support the statistics of currentEmitEventTimeLag, it needs to provide a timestamp when data enters Paimon and emit it in the Flink source.

### Anything else?

Perhaps we can provide a record timestamp for each record, like Kafka does, to make it a writing metadata and reading metadata in Flink.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Related: https://github.com/apache/incubator-paimon/pull/1735

**Comment by Tan-JiaLiang** [comment]
Closed: #2574
