### ISSUE TITLE
[Feature] Support count on files and manifest list name show on snapshots table

### ISSUE THREAD

**Issue by schnappi17** [apache/incubator-paimon#1773]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Support count on files and manifest list name show on snapshots table

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
This change will make the snapshots table completely unusable:
1. Firstly, it will be very slow, and each snapshot will scan and read all the files.
2. Secondly, this scan does not contain filters for partitions, which is highly likely to cause OOM.

**Comment by JingsongLi** [comment]
CC @schnappi17 @FangYongs

**Comment by JingsongLi** [comment]
And please do not add fields in the middle of the schema as this will compromise previous compatibility.
