### ISSUE TITLE
[Bug] Deletion fails in Flink SQL Client with an UnsupportedOperationException

### ISSUE THREAD

**Issue by Begunner** [apache/incubator-paimon#1788]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

Paimon 0.4.0-incubating

### Compute Engine

flink-1.17.0

### Minimal reproduce step

Following https://paimon.apache.org/docs/0.4/concepts/file-operations/
1. Create the catalog and the table in Flink SQL Client and insert some lines into the table. 
2. Set runtime-mode to 'batch'.
3. Try to delete some of the lines. 

### What doesn't meet your expectations?

Throwing an exception:
```
[ERROR] Could not execute SQL statement. Reason:
java.lang.UnsupportedOperationException: Can't perform delete operation of the table paimon.default.T because the corresponding dynamic table sink has not yet implemented org.apache.flink.table.connector.sink.abilities.SupportsRowLevelDelete.
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
Hi, this is because DELETE/UPDATE syntax is supported in Paimon-0.5 (current master). Please use 0.5 snapshot jar to do the test.
