### ISSUE TITLE
[Bug] Unstable Test case MySqlSyncDatabaseTable

### ISSUE THREAD

**Issue by legendtkl** [apache/incubator-paimon#1799]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

flink

### Minimal reproduce step

<img width="636" alt="image" src="https://github.com/apache/incubator-paimon/assets/2370761/56d9cdc7-8648-4149-8c00-2ea700b8ae0e">

https://github.com/apache/incubator-paimon/actions/runs/5830902368/job/15813230854?pr=1734

### What doesn't meet your expectations?

make it stable

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
I think #1783 fixes it.
