### ISSUE TITLE
[Feature] Support storing the commit ID and packaging time inside the JAR,when building a JAR package with Paimon

### ISSUE THREAD

**Issue by wg1026688210** [apache/incubator-paimon#1820]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

It is necessary to record the commit ID and build time inide jar for easy tracking of code versions when using a jar package built from a specific version of the master branch to experience the latest features.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhu3pang** [comment]
i wander is this what you want? the image is the git log output

<img width="772" alt="image" src="https://github.com/apache/incubator-paimon/assets/19250651/0ee48a08-7b9b-4b25-ae26-c8c6cd3c5c1f">
and the META-INF/MANIFEST.MF content:  SCM-Revision: 58cd5a58306cd00b07eff56875206b0e49e38269

```
Manifest-Version: 1.0
Implementation-Title: Paimon : Common
Implementation-Version: 0.5-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: zhujing
Specification-Vendor: The Apache Software Foundation
Specification-Title: Paimon : Common
Implementation-Vendor-Id: org.apache.paimon
Implementation-Vendor: The Apache Software Foundation
SCM-Revision: 58cd5a58306cd00b07eff56875206b0e49e38269
Created-By: Apache Maven 3.9.3
Build-Jdk: 1.8.0_382
Specification-Version: 0.5-SNAPSHOT
```

**Comment by wg1026688210** [comment]
Good Job ! @zhu3pang  , this can meet my needs. I haven't found SCM-Revision in the Paimon flink jar yet. Does this require additional development?

**Comment by zhu3pang** [comment]
@wg1026688210  use the `git-commit-id-plugin` , then add `SCM-Revision` property to the `maven-jar-plugin`, here is the patch
[scm.patch](https://github.com/apache/incubator-paimon/files/12390405/scm.patch)

**Comment by JingsongLi** [comment]
@wg1026688210 @zhu3pang Sounds good to me~

**Comment by wg1026688210** [comment]
hi~ @zhu3pang Would you like to create a pr to fininsh it.

**Comment by zhu3pang** [comment]
@wg1026688210 sure, i will create a pr later
