### ISSUE TITLE
[Bug] SparkGenericCatalog can not show paimon tables;

### ISSUE THREAD

**Issue by hdygxsj** [apache/incubator-paimon#1855]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5.0

### Compute Engine

spark

### Minimal reproduce step

1、create catalog use SparkGennericCatalog
2、create paimon table
3、show tables

### What doesn't meet your expectations?

The show tables command cannot show the paimon table
It may be caused by the listTables method returns only the tables in the sessionCatalog
<img width="814" alt="截屏2023-08-21 15 27 46" src="https://github.com/apache/incubator-paimon/assets/35210666/2211d656-79e7-4907-8ef5-aa913abd8534">

### Anything else?

Is this paimon's design or a Bug? If it is a Bug, I am willing to fix it

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
This is by design, we expect using Hive metastore, then there should be good an experience.

**Comment by hdygxsj** [comment]
No Bug
