### ISSUE TITLE
[Bug] When hive queries the partition table with the metastore.partitioned-table parameter added to ddl, the timestamp type data is inconsistent with the actual data. Procedure

### ISSUE THREAD

**Issue by Dkbei** [apache/incubator-paimon#1865]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

Software version：
flink: 1.14.6
flink-paimon:paimon-flink-1.14-0.5-20230822.001840-132.jar
paimon hive connector: paimon-hive-connector-2.1-cdh-6.3-0.5-20230822.001840-128.jar

### Compute Engine

hive:2.1.0-cdh6.3.2

### Minimal reproduce step

flink table ddl:
create table paimon.ods.students
(id                                                                  decimal(20,0) 
,upload_insert                                                       TIMESTAMP               
,dt                                                                  string
,PRIMARY KEY(id,dt) NOT ENFORCED
) PARTITIONED BY (dt)
WITH (
  'bucket' = '-1', 
  'dynamic-bucket.target-row-num'='5000000',
  'dynamic-bucket.assigner-parallelism' = '1',
  'write-only' = 'false',
  'scan.mode' = 'latest-full',
  'write-buffer-spillable' = 'true',
  'read.batch-size' = '1024',
  'path' = 'hdfs://xx/user/hive/warehouse/ods.db/students',
  'snapshot.time-retained' = '1 h',
  'target-file-size' = '120 mb',
  'num-sorted-run.compaction-trigger' = '10',
  'write-buffer-size' = '256 mb',
  'file.format' = 'parquet',
  'full-compaction.delta-commits' = '10',
  'file.compression.per.level' = '0:SNAPPY,1:SNAPPY',
  'metastore.partitioned-table' = 'true'
);

insert into paimon.ods.students2 select cast(1 as decimal(20,0)) as id,to_timestamp('2023-08-01 14:03:00') as upload_insert,'20230801' as dt;

create table paimon.ods.students1
(id                                                                  decimal(20,0) 
,upload_insert                                                       TIMESTAMP               
,dt                                                                  string
,PRIMARY KEY(id,dt) NOT ENFORCED
) PARTITIONED BY (dt)
WITH (
  'bucket' = '-1', 
  'dynamic-bucket.target-row-num'='5000000',
  'dynamic-bucket.assigner-parallelism' = '1',
  'write-only' = 'false',
  'scan.mode' = 'latest-full',
  'write-buffer-spillable' = 'true',
  'read.batch-size' = '1024',
  'path' = 'hdfs://xx/user/hive/warehouse/ods.db/students1',
  'snapshot.time-retained' = '1 h',
  'target-file-size' = '120 mb',
  'num-sorted-run.compaction-trigger' = '10',
  'write-buffer-size' = '256 mb',
  'file.format' = 'parquet',
  'full-compaction.delta-commits' = '10',
  'file.compression.per.level' = '0:SNAPPY,1:SNAPPY'
);

insert into paimon.ods.students1 select cast(1 as decimal(20,0)) as id,to_timestamp('2023-08-01 14:03:00') as upload_insert,'20230801' as dt;

### What doesn't meet your expectations?

table ods.students:
<img width="385" alt="image" src="https://github.com/apache/incubator-paimon/assets/38800374/855ff1e7-9a8d-457d-a2f8-288b33d3425e">

table ods.student1:
<img width="389" alt="image" src="https://github.com/apache/incubator-paimon/assets/38800374/41c8e328-2ce4-4c66-8e90-dc74f433d6c4">

The structure of the two tables was the same, but the parameter metastore.partitioned-table was removed for student2, and the timestamp column of the student query result was inconsistent with the write result.

### Anything else?

Currently, the paimon hive connector does not support writing data to the dynamic bucket splitting table through hive. Is it supported in the future?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
I'm going to try to fix this.

**Comment by Alibaba-HZY** [comment]
> I'm going to try to fix this.

i tried to fix it. but i do not know why partition table used getPrimitiveWritableObject method and non-partition used getPrimitiveJavaObject.if you fix it please tell me
