### ISSUE TITLE
[Feature] --table-prefix prefix setting is invalid

### ISSUE THREAD

**Issue by xiaolin84250** [apache/incubator-paimon#1902]
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

The version I use is 【paimon-flink-action-0.5-20230828.001918-122.jar】. Just now, I tested that using --table-prefix to add a prefix is invalid, but using --table-suffix to add a suffix is valid, and If the above two are used at the same time when the whole library is synchronized, the prefix will become a suffix.

The command used is as follows:
```
bin/flink run \
    /opt/flink-1.17.0/paimon-flink-action-0.5-20230828.001918-122.jar \
    mysql-sync-database \
    --warehouse hdfs://master:8020/paimon/fs \
    --database test \
    --table-prefix "ods_" \
    --table-suffix "_cdc" \
    --mysql-conf hostname=slave2 \
    --mysql-conf username=root \
    --mysql-conf password=root \
    --mysql-conf database-name=gmall \
    --table-conf bucket=4 \
    --table-conf changelog-producer=input \
    --table-conf sink.parallelism=4
```

```
bin/flink run \
    /opt/flink-1.17.0/paimon-flink-action-0.5-20230828.001918-122.jar \
    mysql-sync-database \
    --warehouse hdfs://master:8020/paimon/fs \
    --database test1 \
    --table-prefix "ods_" \
    --table-suffix "_cdc" \
    --mysql-conf hostname=slave2 \
    --mysql-conf username=root \
    --mysql-conf password=root \
    --mysql-conf database-name=gmall \
    --table-conf bucket=4 \
    --table-conf changelog-producer=input \
    --table-conf sink.parallelism=4 \
    --including-tables 'activity_info|base_category1'
```

### Solution

It is not resolved yet.

### Anything else?

cdc whole library synchronization：
![](https://ylw-typora-img.oss-cn-chengdu.aliyuncs.com/img/202308281606534.png)

![image](https://github.com/apache/incubator-paimon/assets/38107489/77813714-43b6-41fa-8be3-01730a29d10a)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by MonsterChenzhuo** [comment]
@xiaolin84250 We are also using this mysql into the lake, I will see what causes it tomorrow

**Comment by MonsterChenzhuo** [comment]
@xiaolin84250  I didn't find this problem today using the latest dev code

**Comment by xiaolin84250** [comment]
The new version is no problem, thank you.
