### ISSUE TITLE
[Feature] add uuid and createtime of table

### ISSUE THREAD

**Issue by miomiocat** [apache/incubator-paimon#1917]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

An identifier is expected to distinguish different tables, including rebuilt tables with the same name.

background:
it will be used to connect to the authority system

### Solution

similar solution: uuid of table meta in iceberg table

https://github.com/apache/iceberg/pull/264

Or just save the create time of table

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhu3pang** [comment]
https://github.com/apache/incubator-paimon/pull/1716 can resolve your problem?

**Comment by miomiocat** [comment]
> #1716 can resolve your problem?

Will this record the time when the table was created with no shema change?

and it would be better to provide an upper layer interface like `org.apache.paimon.table.Table.getCreateTime()` for access

**Comment by miomiocat** [comment]
@zhu3pang 

Thanks again.  
We found a solution now and closed this issue.
