### ISSUE TITLE
[Feature] Streaming reading with consumer-id, the full-load phase may lead to checkpoint failure.

### ISSUE THREAD

**Issue by ChenlingXie** [apache/incubator-paimon#1941]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation
Append Only Table.
Streaming reading with consumer-id, the full-load phase must be completed before the first checkpoint timeout, and if there is a large amount of full-load data to be read, an extended timeout period is required.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ChenlingXie** [comment]
closed by pr https://github.com/apache/incubator-paimon/pull/2221

**Comment by scottxing** [comment]
@ChenlingXie Paimon version 0.7, when a large amount of data passes through paimon cdc, about 100 million records are dropped to the paimon ods table. The table attribute sets changelog as input. Then, at this time, I write a flink sql job (using the consumer-id setting), and read This table is inserted into another paimon dwd table (the changelog attribute is lookup). After starting this job, the checkpoint has been stuck at 0% and cannot be completed, so the snapshot cannot be committed. As a result, my other flink sql job cannot check the paimon dwd table. to data. This leads to the phenomenon that a large amount of data from one paimon table must be completely written to another paimon table before it can then be transferred from this paimon table to the next. Data cannot flow smoothly from job to job like a stream. How to solve it?
