### ISSUE TITLE
[Feature] Support scan metrics

### ISSUE THREAD

**Issue by schnappi17** [apache/incubator-paimon#2000]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Subtask of [PIP-3](https://cwiki.apache.org/confluence/display/PAIMON/PIP-3%3A+Introduce+metrics+for+Paimon)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Aitozi** [comment]
Hi @schnappi17 , are there a document about the metrics already added ?
