### ISSUE TITLE
[CI] Added CI for Flink CDC test running on JDK11

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-paimon#2005]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Added CI for Flink CDC test running on JDK11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Jake-00** [comment]
Hi, @zhuangchong. I am insterested in this issue. Could you asign to me
