### ISSUE TITLE
[Feature] Support to set the table option by dynamic global job configuration 

### ISSUE THREAD

**Issue by Aitozi** [apache/incubator-paimon#2037]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

When using Flink to query the Paimon table, supporting overwriting the catalog table option by `SET` syntax will be more convenient. The dynamic options can only take effect in the current session.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
> In my current implementation, we inject the options with the specific prefix in flink config to the table option. So the requirements like #1943 can also be done without introducing more new configs.
> 
> WDYT @JingsongLi

Sounds good to me, actually, I think it is good to introduce this mechanism in reviewing for #1943
