### ISSUE TITLE
[Feature]  CDC Ingestion supports double-write kafka

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/incubator-paimon#2063]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

At present, if users have a reuse requirement for CDC (Change Data Capture) synchronized data, we recommend that users first import the data into Kafka (where Kafka data is used for reuse) and then from Kafka to Paimon. Based on this scenario, I am considering taking an action to write to Paimon, while also writing a copy of the changelog to Kafka, which can simplify the synchronization link.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
It is not recommended. Kafka external log is deprecated.
