### ISSUE TITLE
[Feature] [PaimonCDC]Add extra checker for decimal type

### ISSUE THREAD

**Issue by hk-lrzy** [apache/incubator-paimon#2128]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

In my case
old type:`decmial(35,9)`.
new type `decimal(20,3)`.

I think there no need changes for `ScheamManager` in paimon, So i want to add more check for the `UpdatedDataFieldsProcessFunctionBase`

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Please use `fix issue` in the PR.
