### ISSUE TITLE
[Feature] Bump Parquet version to 1.13.1

### ISSUE THREAD

**Issue by zhongyujiang** [apache/incubator-paimon#2137]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

This update fixs a critical parquet/zstd memory issue: [PATQUET-2160](https://github.com/apache/parquet-mr/pull/982), besides it brings support for [LZ4_RAW codec](https://issues.apache.org/jira/browse/PARQUET-2196).
More details are in the release notes:
1.13.1: https://github.com/apache/parquet-mr/blob/master/CHANGES.md#version-1131
1.13.0: https://github.com/apache/parquet-mr/blob/master/CHANGES.md#version-1130

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhongyujiang** [comment]
I think fixing the parquet/zstd issue would be great and this update should be safe, as I know both Apache Spark and Apache Iceberg have been working on 1.13.1 for some time. 
I'd like to pull a PR to close this, but according to the contribution guide, the community prefers contributors `Only create the PR if you are assigned to the issue.`  So @JingsongLi, could you take a look at this?  Thanks!

**Comment by zhongyujiang** [comment]
@yuzelin Hi, maybe you could take a look at this?  Thanks.

**Comment by JingsongLi** [comment]
I am OK with the bumping.
