### ISSUE TITLE
[Feature] Remove the parquet-avro dep from paimon-formt

### ISSUE THREAD

**Issue by zhongyujiang** [apache/incubator-paimon#2138]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Paimon-format project adds dependency for [parquet-avro](https://github.com/apache/incubator-paimon/blob/db50fb2b24523d9bcd16aa041f9d771cbb61c4ce/paimon-format/pom.xml#L141-L145), however it's never used in this project. Seems that we should remove the parquet-avro dep.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhongyujiang** [comment]
Hi @JingsongLi, please take a look at this too. 
I've checked that Parquet-avro is indeed not used in this project, I think is always good to remove the useless deps.

**Comment by JingsongLi** [comment]
> Hi @JingsongLi, please take a look at this too. I've checked that Parquet-avro is indeed not used in this project, I think is always good to remove the useless deps.

Thanks @zhongyujiang ! Merged!
