### ISSUE TITLE
[Feature] Introduce BranchManager for branch

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#2148]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

subtask of #1795

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by TaoZex** [comment]
I would like to solve this issue, please assign to me. Thanks!
