### ISSUE TITLE
[Bug] writing to primary key, the temporary file "paimon-io-xxx" would not be deleted in time.

### ISSUE THREAD

**Issue by leaves12138** [apache/incubator-paimon#2171]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6-SNAPSHOT

### Compute Engine

FLINK

### Minimal reproduce step

insert into pk select * from datagen;

### What doesn't meet your expectations?

no paimon-io-xxx data left always.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
#2174 This PR should solve this issue.

**Comment by zhuangchong** [comment]
Already solved.
