### ISSUE TITLE
When using the MySQL CDC synchronization tool, I found that the --metadata-column parameter, specifically op_ts, cannot be properly converted from a timestamp to TIMESTAMP_LTZ(3).

### ISSUE THREAD

**Issue by labixiaoxiaopang** [apache/incubator-paimon#2182]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6-SNAPSHOT

### Compute Engine

flink: 1.17.1
flink cdc: 2.3

### Minimal reproduce step

> 1：use paimon-flink-action-0.6-SNAPSHOT.jar

> 2： use param --metadata-column op_ts,database_name,table_name

> 3：I've noticed that there's no tm_ms field in the org.apache.paimon.flink.action.cdc.mysql.format.DebeziumEvent file under the public class Source. I added this field, thinking I had solved the issue. 

> 4：However, during the usage, I found that the op_ts field is using the org.apache.paimon.utils.TypeUtils utility for conversion, and I traced it to the castFromStringInternal method. It appears that TIMESTAMP_WITHOUT_TIME_ZONE cannot properly convert the timestamp.

### What doesn't meet your expectations?

**I would like the op_ts field to be written as either a timestamp or a bigint type.**

### Anything else?

**1：Why isn't the data type of the op_ts field bigint?**

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
I will solve this issue.
