### ISSUE TITLE
[Feature] Add kafka properties to kafka log store register

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#2208]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently only `bootstrap.servers` is added to the properties for `KafkaLogStoreRegister`. We need to add all kafka relevant properties to kafka log store register for authentication

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
Can you assign this task to me?

**Comment by schnappi17** [comment]
> Can you assign this task to me?

@zhuangchong Hi Chong, I'm working on this, sorry for the late information.
