### ISSUE TITLE
[Bug] flink can not streaming read the deleted data

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/incubator-paimon#2246]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

flink

### Minimal reproduce step

1. `CREATE TABLE t1 (id INT PRIMARY KEY NOT ENFORCED, name STRING)`
2. start a new flink client to streaming the table `t1`
3. in the previous flink client, `INSERT INTO t1 SELECT 1,'aa'` , `DELETE FROM t1`
4. the flink streaming job , it can read the INSERT data . can not read the DELETE data

### What doesn't meet your expectations?

flink streaming job can read the delete data

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by labixiaoxiaopang** [comment]
1:check  this configuration changelog-producer
2:check  this configuration changelog-producer.row-deduplicate
