### ISSUE TITLE
[Feature] Migrate the exist hive table to paimon append-only table

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/incubator-paimon#2249]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

We can introduce an action to help user to migrate the exist hive table to paimon append-only table without move the data when users want to upgrade their hive data warehouse to paimon .

we can use the origin hive data (orc or parquet file) ,and generate the paimon metadata for the hive file.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Hi @zhangjun0x01 , @leaves12138 is doing this work. It is complex.

**Comment by zhuangchong** [comment]
#2368 done.
