### ISSUE TITLE
[Bug] Streaming writes to a Deduplicate table, flink job can't recover for FileNotFoundException

### ISSUE THREAD

**Issue by bridgeDream** [apache/incubator-paimon#2273]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6-SNAPSHOT

### Compute Engine

Flink 1.16.1

### Minimal reproduce step

1. DDL 
`CREATE TABLE IF NOT EXISTS paimon_catalog.dim.event_log_aggregation(
  order_no string,
  new_status int,
  creator string ,
  id bigint,
  create_time timestamp COMMENT '日志创建时间',
  version bigint COMMENT '与 create_time 反相关',
  PRIMARY KEY (order_no, new_status) NOT ENFORCED
) with (
    'merge-engine' = 'Deduplicate',
    'sequence.field' = 'version'
);`
2. starting a flink job (consume kafka and write into paimon)
3. waiting some time, stop flink job with a savepoint 
4. recover flink job with savepoint, flink job throw exception
![image](https://github.com/apache/incubator-paimon/assets/96433131/d194a13e-2625-4ec5-a7b1-7c571e01618a)
5. restart flink job without savepoint, but same exception is occur

### What doesn't meet your expectations?

Even though I restarted the flink task stateless to write into paimon, the same error occurred:
FileNotFoundException

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
It seems like you have recovered your job from an older savepoint.
If you are just using stop with savepoint, and recover your job, it is impossible to have this problem.

**Comment by JingsongLi** [comment]
But I will add check to avoid this situation.
