### ISSUE TITLE
[Improvement] Keep a single META-INF directory at the root level for paimon-s3

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#2413]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Paimon placed S3 related classes in the `paimon-plugin-s3` directory in order to implement the Plugin mechanism for Classloader isolation, which can prevent these classes from entering the default classloader and causing class conflicts.

But the `META-INF` directory has also been moved to a subdirectory, a better way is to place `META-INF` in the root directory.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by pegasas** [comment]
Thanks for this issue coming up.
I create an PR for fixing this. feel free to comments if any concerns.
