### ISSUE TITLE
[Bug] can not streaming read empty table correctly in `latest` mode

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/incubator-paimon#2588]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6

### Compute Engine

flink

### Minimal reproduce step

1. `create table t1(id int ,name string)`
2. start another job to streaming read the table `t1` : `select  * from t1 /*+ OPTIONS('scan.mode'='latest') */`
3. generate 2 snapshot: `insert into t1 select 1,'a' `, `insert into t1 select 2,'b'`
4. the streaming read job can not get the data `1,'a'` (snapshot 1), only get the data `2,'b'`

### What doesn't meet your expectations?

 the streaming read job can not get the data `1,'a'`, only get the data `2,'b'`

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
'latest' won't read the first snapshot when starting; If you use 'latest-full', you can get desired results.
