### ISSUE TITLE
[Feature] Compatible with upper and lower case when use hivesql queries paimon external table

### ISSUE THREAD

**Issue by gnailJC** [apache/incubator-paimon#2634]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

1. use sparksql wirte data into a paimon table(has upper case fields) by filesystem-catalog
2. use hivesql to create a paimon external table
3. use hivesql `select upperCaseField(or uppercasefield) from paimon external table` can work

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
I can fix it
