### ISSUE TITLE
[Bug] Using Hive SQL to perform is not null query but the returned result still contains null

### ISSUE THREAD

**Issue by gnailJC** [apache/incubator-paimon#2663]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master-0.7

### Compute Engine

hive

### external table schema:

> | _id                                  | string                                             |          |
> | equityalterlist                      | array<struct<alterdate:string,name:string,postalter:double,prealter:double,publicdate:string>> |   

       

### query sql:

> select `_id`, equityalterlist  from enterprise where equityalterlist is not null limit 10;

### result

> +---------------+------------------+
> |      _id      | equityalterlist  |
> +---------------+------------------+
> | 1  | NULL             |
> | 2  | NULL             |
> | 3  | NULL             |
> | 4  | NULL             |
> | 5  | NULL             |
> | 6  | NULL             |
> | 7  | NULL             |
> | 8  | NULL             |
> | 9  | NULL             |
> +---------------+------------------+

### explain 

> +----------------------------------------------------+
> |                      Explain                       |
> +----------------------------------------------------+
> | STAGE DEPENDENCIES:                                |
> |   Stage-0 is a root stage                          |
> |                                                    |
> | STAGE PLANS:                                       |
> |   Stage: Stage-0                                   |
> |     Fetch Operator                                 |
> |       limit: 10                                    |
> |       Processor Tree:                              |
> |         TableScan                                  |
> |           alias: enterprise                        |
> |           properties:                              |
> |             insideView TRUE                        |
> |           Statistics: Num rows: xxx Data size: xxx Basic stats: COMPLETE Column stats: NONE |
> |           Select Operator                          |
> |             expressions: _id (type: string), equityalterlist (type: array<struct<alterdate:string,name:string,postalter:double,prealter:double,publicdate:string>>) |
> |             outputColumnNames: _col0, _col1        |
> |             Statistics: Num rows: xxx Data size: xxx Basic stats: COMPLETE Column stats: NONE |
> |             Limit                                  |
> |               Number of rows: 10                   |
> |               Statistics: Num rows: 10 Data size: xxx Basic stats: COMPLETE Column stats: NONE |
> |               ListSink                             |
> |                                                    |
> +----------------------------------------------------+

### What doesn't meet your expectations?

How should I configure it so that `is not null` in hivesql has the same effect as sparksql.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gnailJC** [comment]
@zhuangchong Could you please tell me if there is any relevant solution to this issue?

**Comment by zhuangchong** [comment]
I haven't reproduced your problem locally. What is your table creation statement? What is the operation process?

![image](https://github.com/apache/incubator-paimon/assets/37063904/072143a9-1cc5-4270-8a25-22a15dfa7f52)

**Comment by gnailJC** [comment]
> I haven't reproduced your problem locally. What is your table creation statement? What is the operation process?
> 
> ![image](https://private-user-images.githubusercontent.com/37063904/295132860-072143a9-1cc5-4270-8a25-22a15dfa7f52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTE5OTIsIm5iZiI6MTcwNDc5MTY5MiwicGF0aCI6Ii8zNzA2MzkwNC8yOTUxMzI4NjAtMDcyMTQzYTktMWNjNS00MjcwLThhMjUtMjJhMTVkZmE3ZjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5MTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZmNlZGJjMmJhZjM3Yzg2ZDE0OTc0ZWVmMWRmZmE0ZTE1ZjU3YmY4NGYxM2JlNGUwMDQwZmRhZjc3Mjg0ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2s1mFFslw5ZFLKtBlzA-naHhLaus03kk_o4aV5Zc6mk)

Thanks for your reply! 

show create table:

> CREATE EXTERNAL TABLE `enterprise` (
>   _id string,
>   equityalterlist ARRAY <structalterdate: string, name: string, postalter: DOUBLE, prealter: DOUBLE, publicdate: string >
> ) 
> ROW FORMAT SERDE 'org.apache.paimon.hive.PaimonSerDe' 
> STORED BY 'org.apache.paimon.hive.PaimonStorageHandler' 
> WITH SERDEPROPERTIES ('serialization.format' = '1') 
> LOCATION 'oss://xxx' 
> TBLPROPERTIES (
>   'bucketing_version' = '2',
>   'last_modified_time' = '1704787843',
>   'transient_lastDdlTime' = '1704787843'
> )

steps:

1. [spark3.3 dataframe&structed streaming] use spark to write a  paimon table in oss
2. [hivesql3.1] CREATE EXTERNAL TABLE IF NOT EXISTS enterprise STORED BY 'org.apache.paimon.hive.PaimonStorageHandler' LOCATION 'oss://xxxx';
3. [hivesql3.1] select _id, equityalterlist from enterprise where equityalterlist is not null limit 10;

**Comment by zhangjun0x01** [comment]
it is a bug for hive, when the cbo optimization of hive is enabled, will cause incorrect results in query `struct` type with `not null` predicate, and you can disable the cbo by `set hive.cbo.enable=false`

**Comment by gnailJC** [comment]
> it is a bug for hive, when the cbo optimization of hive is enabled, will cause incorrect results in query `struct` type with `not null` predicate, and you can disable the cbo by `set hive.cbo.enable=false`

thanks ! It is work by `set hive.cbo.enable=false`.
