### ISSUE TITLE
[Bug] Using param “--type_mapping to-string” is not valid

### ISSUE THREAD

**Issue by ElancerBlack** [apache/incubator-paimon#2704]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

paimon0.6.0

### Compute Engine

flink-1.17.0

### Minimal reproduce step

bin/flink run \
    /data1/module/flink-1.17.0/jars/paimon-flink-action-0.6.0-incubating.jar \
    mysql-sync-table \
    --warehouse hdfs://test202:9000/paimon/hive  \
    --database default \
    --table test_cdc_zzj_3\
    --partition-keys partdate \
    --primary-keys partdate,id \
    --type_mapping to-string \
    --computed-column 'partdate=date_format(create_time, 'yyyyMMdd')' \
    --mysql-conf hostname=test201 \
    --mysql-conf username=root \
    --mysql-conf password=123456 \
    --mysql-conf database-name=test \
    --mysql-conf table-name='test_.*' \
    --catalog-conf metastore=hive \
    --catalog-conf uri=thrift://test202:9083 \
    --table-conf bucket=4 \
    --table-conf changelog-producer=input \
    --table-conf sink.parallelism=1

### What doesn't meet your expectations?

![image](https://github.com/apache/incubator-paimon/assets/35108207/e7c451e1-9204-4605-88b7-fe010b46eee3)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by TaoZex** [comment]
I will fix this issue, please assign to me. Thanks @yuzelin

**Comment by TaoZex** [comment]
I did a replay on the latest dev release and did not find this problem.

**Comment by ElancerBlack** [comment]
> I did a replay on the latest dev release and did not find this problem.

but this release is 0.6.0,not the latest dev. I will try to use it to replay

**Comment by ElancerBlack** [comment]
> I did a replay on the latest dev release and did not find this problem.

it‘s ok，thank you so much!
