### ISSUE TITLE
[Feature] Add Procedure in flink for creating and deleting branch

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#2723]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

subtask of #1795 Add `Procedure` in flink to support creating and deleting branch

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by TaoZex** [comment]
Please assign to me. Thanks @FangYongs . I will continue to improve the branch feature.

**Comment by FangYongs** [comment]
@TaoZex I have create a PR for it, you can help to review it, thanks

**Comment by TaoZex** [comment]
@FangYongs Thanks for your response. I have reviewed it.
