### ISSUE TITLE
[Bug] Official website spark jumps 404

### ISSUE THREAD

**Issue by Xikl** [apache/incubator-paimon#2737]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

最新版

### Compute Engine

spark

### Minimal reproduce step

![image](https://github.com/apache/incubator-paimon/assets/28380675/5f606e41-8498-4eb4-a8c6-bc26f7b53f46)
从官网的spark进去回到这个地址：https://paimon.apache.org/docs/master/engines/spark3/ 404，应改成https://paimon.apache.org/docs/master/engines/spark/

### What doesn't meet your expectations?

地址跳转

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
This Issue has been fixed https://github.com/apache/incubator-paimon-website/pull/2

**Comment by yuzelin** [comment]
Maybe you need to clear your browser cache.
