### ISSUE TITLE
[Feature] Support compiled class cache in CodeGenUtils

### ISSUE THREAD

**Issue by xiangyuf** [apache/incubator-paimon#2955]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

![screenshot-20240306-171507](https://github.com/apache/incubator-paimon/assets/3021821/70b63f59-b75d-4146-8002-ab55d2bf65ee)

When we have a table with thousands of columns, the operation to generate a RecordEqualiser class will consume lots of resources. Especially when we are creating multiple Readers from multiple Table instances at the same time, this is a real case when reading the paimon table using Starrocks as external tables. By reusing the generated class, we can avoid this problem.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Here should have a cache... But I forgot this...
@xiangyuf Thanks for reporting, feel free to open PR, I will take a review.

**Comment by xiangyuf** [comment]
> Here should have a cache... But I forgot this... @xiangyuf Thanks for reporting, feel free to open PR, I will take a review.

Hi @JingsongLi , would kindly assign this issue to me?
