### ISSUE TITLE
[Feature] Make `forceCreatingSnapshot` a toggle option for paimon

### ISSUE THREAD

**Issue by huyuanfeng2018** [apache/incubator-paimon#2957]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

PaimonSink Commit has a logic that if no data is written during a checkpoint cycle, no snapshot will be generated.
Let me give you an example:

If I read a kafka stream and write it to Paimon, there may be filters in the middle, and flink watermarks are generated at the same time. Then each snapshot of Paimon will have watermark information. I can judge my writing progress through the watermark of the latest snapshot. , if the watermark is advancing in a checkpoint interval, but the filter logic filters out the data, a snapshot will not be generated, but the watermark should be advancing.

Currently, forced snapshot generation only takes effect when the automatic tag creation configuration is enabled and certain conditions are met. I think we should make this a switchable option.

### Solution

Make `forceCreatingSnapshot` a toggle option for paimon

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by huyuanfeng2018** [comment]
@JingsongLi  WDYT? Can you give some advice

**Comment by JingsongLi** [comment]
This requirement looks good to me!
@huyuanfeng2018 Feel free to open PR, I will take a review.

**Comment by huyuanfeng2018** [comment]
> This requirement looks good to me! @huyuanfeng2018 Feel free to open PR, I will take a review.

Thank you for your reply, I will open a PR later.
