### ISSUE TITLE
[Feature] Support limit push down on hive

### ISSUE THREAD

**Issue by gnailJC** [apache/incubator-paimon#2994]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Support limit push down on hive for improving query performance.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gnailJC** [comment]
@zhuangchong Hi, is it possible to implement limit push down when querying paimon on hive? Like the current implementation of spark and flink?

**Comment by zhuangchong** [comment]
I did not find how to get the limit parameter value from hive query sql.
