### ISSUE TITLE
[Bug] Paimon can not working with iceberg

### ISSUE THREAD

**Issue by BsoBird** [apache/incubator-paimon#3030]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.7

### Compute Engine

spark 3.4.1

### Minimal reproduce step

https://github.com/apache/iceberg/issues/8624

### What doesn't meet your expectations?

https://github.com/apache/iceberg/issues/8624

### Anything else?

https://github.com/apache/iceberg/issues/8624

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by BsoBird** [comment]
Hello. can anyone help me?

**Comment by JingsongLi** [comment]
Hi @BsoBird , can you show me the startup command of Spark SQL?

**Comment by BsoBird** [comment]
/data/kyuubi/spark-3.4.1-bin-hadoop3/bin/spark-submit \
        --class org.apache.kyuubi.engine.spark.SparkSQLEngine \
        --conf spark.hive.default.fileformat=orc \
        --conf spark.hive.default.fileformat.managed=orc \
        --conf spark.hive.metastore.dml.events=false \
        --conf spark.kyuubi.authentication.ldap.base.dn=ou=people,dc=hadoop,dc=apache,dc=org \
        --conf spark.kyuubi.client.ipAddress=192.168.189.52 \
        --conf spark.kyuubi.engine.engineLog.path=/data/kyuubi/kyuubi/work/hive_read/kyuubi-spark-sql-engine.log.0 \
        --conf spark.kyuubi.engine.submit.time=1701740001759 \
        --conf spark.kyuubi.ha.addresses=192.168.178.171:2181,192.168.178.172:2181,192.168.178.173:2181,192.168.178.174:2181,192.168.178.175:2181 \
        --conf spark.kyuubi.ha.client.class=org.apache.kyuubi.ha.client.zookeeper.ZookeeperDiscoveryClient \
        --conf spark.kyuubi.ha.engine.ref.id=1860efa5-b869-45dc-859d-405247f13a79 \
        --conf spark.kyuubi.ha.namespace=/kyuubi_1.6.1_1.8.0_USER_SPARK_SQL/hive_read/default \
        --conf spark.kyuubi.server.ipAddress=192.168.178.140 \
        --conf spark.kyuubi.session.conf.advisor=org.apache.kyuubi.plugin.JdbcSessionAdvisor \
        --conf spark.kyuubi.session.connection.url=smaster01:10009 \
        --conf spark.kyuubi.session.engine.idle.timeout=PT10H \
        --conf spark.kyuubi.session.engine.initialize.timeout=360000 \
        --conf spark.kyuubi.session.engine.login.timeout=60 \
        --conf spark.kyuubi.session.real.user=hive_read \
        --conf spark.app.name=kyuubi_USER_SPARK_SQL_hive_read_default_1860efa5-b869-45dc-859d-405247f13a79 \
        --conf spark.driver.cores=4 \
        --conf spark.driver.memory=8g \
        --conf spark.dynamicAllocation.enabled=true \
        --conf spark.dynamicAllocation.executorIdleTimeout=3600s \
        --conf spark.dynamicAllocation.initialExecutors=5 \
        --conf spark.dynamicAllocation.maxExecutors=5 \
        --conf spark.dynamicAllocation.minExecutors=5 \
        --conf spark.executor.cores=8 \
        --conf spark.executor.extraClassPath=jersey-container-servlet-core-2.36.jar,jakarta.ws.rs-api-2.1.6.jar,jersey-server-2.36.jar \
        --conf spark.executor.memory=32g \
        --conf spark.executor.userClassPathFirst=true \
        --conf spark.jars=/data/kyuubi/spark_aux_lib/paimon-spark-3.4-0.6-20231111.001954-55.jar \
        --conf spark.jars.packages=org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.4.2,mysql:mysql-connector-java:5.1.47 \
        --conf spark.kryoserializer.buffer.max=256M \
        --conf spark.master=yarn \
        --conf spark.scheduler.mode=FAIR \
        --conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
        --conf spark.shuffle.service.enabled=true \
        --conf spark.shuffle.service.name=spark2_shuffle \
        --conf spark.sql.adaptive.advisoryPartitionSizeInBytes=256m \
        --conf spark.sql.adaptive.autoBroadcastJoinThreshold=67108864 \
        --conf spark.sql.adaptive.coalescePartitions.enabled=true \
        --conf spark.sql.adaptive.coalescePartitions.initialPartitionNum=8192 \
        --conf spark.sql.adaptive.coalescePartitions.minPartitionNum=1 \
        --conf spark.sql.adaptive.enabled=true \
        --conf spark.sql.adaptive.fetchShuffleBlocksInBatch=true \
        --conf spark.sql.adaptive.forceApply=false \
        --conf spark.sql.adaptive.localShuffleReader.enabled=true \
        --conf spark.sql.adaptive.nonEmptyPartitionRatioForBroadcastJoin=0.2 \
        --conf spark.sql.adaptive.skewJoin.enabled=true

**Comment by BsoBird** [comment]
let me try.

**Comment by BsoBird** [comment]
it works. tks.
