### ISSUE TITLE
[Bug] The TagsTable can not display the different tag name for the same snapshot

### ISSUE THREAD

**Issue by Aitozi** [apache/incubator-paimon#3034]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.8.0

### Compute Engine

core

### Minimal reproduce step

.

### What doesn't meet your expectations?

.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by herefree** [comment]
I will try my best fix this bug,please assign to me.

**Comment by herefree** [comment]
+----------+-------------+-----------+-------------------------+--------------+----------+
| tag_name | snapshot_id | schema_id |             commit_time | record_count | branches |
+----------+-------------+-----------+-------------------------+--------------+----------+
|  my_tag1 |           1 |         0 | 2024-03-18 17:24:41.451 |            1 |       [] |
|  my_tag2 |           1 |         0 | 2024-03-18 17:24:41.451 |            1 |       [] |
|  my_tag3 |           1 |         0 | 2024-03-18 17:24:41.451 |            1 |       [] |
+----------+-------------+-----------+-------------------------+--------------+----------+
I tested it and found that it can be displayed.

**Comment by Aitozi** [comment]
Thanks for your inputs @herefree , It's has been solved be #2765
