### ISSUE TITLE
[Bug] load index too slow when restart flink job using dynamic bucket.

### ISSUE THREAD

**Issue by Stephen0421** [apache/incubator-paimon#3038]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.7

### Compute Engine

Flink

### Minimal reproduce step

Can try to write data using dynamic bucket with datagen generate 0 to 500,000,000 keys, stop the job and restart.

### What doesn't meet your expectations?

This cost around 20 minute to load index, it's too slow.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Stephen0421** [comment]
Can assign the ticket to me? Already have a solution to solve the issue.

**Comment by JingsongLi** [comment]
> Can assign the ticket to me? Already have a solution to solve the issue.

Feel free to open PR. In Paimon community, you don't need to care about issue assigning.
