### ISSUE TITLE
[Bug] Paimon cdc synchronizes the entire database. All job names are duplicates. Prometheus monitoring job names cannot be captured.

### ISSUE THREAD

**Issue by wqlsdb** [apache/incubator-paimon#3053]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.7

### Compute Engine

java api

### Minimal reproduce step

paimon整库同步上生产，prometheus无法抓取job name,因为所有paimon整库同步名称都一样
./bin/flink run -d -t yarn-per-job -Djobmanager.memory.process.size=2096m -Dtaskmanager.memory.process.size=2096m \
-Dyarn.application.queue=spark -Dyarn.application.node-label=ingest -Dyarn.application.name=obei_contract \
/opt/module/flink-1.17.0/lib/paimon-flink-action-0.6.0-incubating.jar \
mysql-sync-database \
--warehouse hdfs://mycluster/user/hive/warehouse/ods.db \
--database ods \
--mysql-conf hostname=10.xx.xx.x.x.xx \
--mysql-conf username=xxxxx \
--mysql-conf password='xxxxxxxx' \
--mysql-conf database-name=obei-contract \
--including-tables 't_dcm_contract_detail|t_dcm_contract_head' \
--catalog_conf metastore=hive \
--catalog_conf uri=thrift://10.80.29.39:9083 \
--table-conf bucket=2 \
--table_prefix t_ods_ \
--table-conf changelog-producer=input \
--table-conf sink.parallelism=2
![image](https://github.com/apache/incubator-paimon/assets/84709143/06d832ae-92a4-43b1-beb7-204faaf4eedc)

### What doesn't meet your expectations?

所有的整库同步job name 一样，不符合

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
You can customize job name, see https://paimon.apache.org/docs/master/cdc-ingestion/overview/#job-name

![image](https://github.com/apache/incubator-paimon/assets/37063904/b3ed6d75-8f57-4177-a25e-9f97ff7800d1)
