### ISSUE TITLE
[Document] Provide jar download url in documentation

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#632]
Now we have already published to snapshot jar to nexus repository.
We can just provide download in documentation, user don't need to build by themselve.

**Comment by zhuangchong** [comment]
What is the address of the nexus repository you speak of?
I found no snapshot of `paimon` in the apache repository `https://www.apache.org/dyn/closer.lua/incubator/paimon`.

**Comment by ai-smalleryu** [comment]
Let me do it

**Comment by JingsongLi** [comment]
> What is the address of the nexus repository you speak of? I found no snapshot of `paimon` in the apache repository `https://www.apache.org/dyn/closer.lua/incubator/paimon`.

You can find them in here: https://repository.apache.org/#nexus-search;quick~paimon

**Comment by JingsongLi** [comment]
> Let me do it

Welcome, you can create PR for this.

**Comment by zhuangchong** [comment]
@ai-smalleryu Hi, is this PR in progress?

**Comment by ai-smalleryu** [comment]
> @ai-smalleryu Hi, is this PR in progress?

I'm working on it, it's almost ready
