### ISSUE TITLE
[Test] Test compatibility to table store 0.3 hive metastore

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#633]
Now after renaming, paimon should be compatibility to table store 0.3 hive metastore.

**Comment by liuxiaocs7** [comment]
Hi, @SteNicholas I am a newcomer for paimon, I want to try this issue, please assign to me, thanks!

**Comment by SteNicholas** [comment]
@liuxiaocs7, welcome to contribute. Please go ahead to push pull request to test compatibility.
