### ISSUE TITLE
[feature] Provide changelog-producer.row-deduplicate to deduplicate same change

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#634]
In `lookup` and `full-compaction` changelog-producer, same record will produce -U and +U, but they are the same.
We can provide a option to avoid producing changelog for the same record.

**Comment by wenlybi** [comment]
I want to do it. Could you assign it to me?

**Comment by Aitozi** [comment]
@JingsongLi Can this option default be true?  Are there use case will rely on the same value -U and +U value ?
