### ISSUE TITLE
[bug][spark] Spark write should work with kryo serializer

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#635]
But `CommitMessageImpl` is not work for kryo, we should fix this.

**Comment by An-DJ** [comment]
Hi, I want to try this. Could u assign it to me? : )

**Comment by JingsongLi** [comment]
@An-DJ feel free to open a pull request.

**Comment by JingsongLi** [comment]
Here we can `WriteRecords` returns `byte[]`. (Use `InstantiationUtil.serializeObject` to convert `CommitMessage` to bytes)
