### ISSUE TITLE
[Feature] Support Datax sink to paimon

### ISSUE THREAD

**Issue by yqzdy1207** [apache/incubator-paimon#648]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

1. 支持Datax读取

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Wow, I think we can create Pull request in https://github.com/alibaba/DataX , I can find maintainers to review~

**Comment by yqzdy1207** [comment]
sorry，datax 已提

**Comment by JingsongLi** [comment]
@yqzdy1207 it is better to use english.
