### ISSUE TITLE
[Bug] Close blocking iterators in tests

### ISSUE THREAD

**Issue by schnappi17** [apache/incubator-paimon#650]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

851e8d432fb35edfc3ed6a836e5cebaa2a0c0aa3

### Compute Engine

Flink

### Minimal reproduce step

Several blocking iterators are not closed in `ContinuousFileStoreITCase`, like in the `testContinuousLatest()`

### What doesn't meet your expectations?

Run unit tests and found this.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by schnappi17** [comment]
@JingsongLi Please help to check if this should be fixed or they are reasonable?

**Comment by JingsongLi** [comment]
@schnappi17 reasonable~ you can create a PR

**Comment by zhuangchong** [comment]
@JingsongLi @schnappi17 This pr has been done, please close this issue.

**Comment by schnappi17** [comment]
@zhuangchong Thanks! Closed.
