### ISSUE TITLE
[Feature] Skip code CI tests if the PR only contains docs change 

### ISSUE THREAD

**Issue by leonardBang** [apache/incubator-paimon#652]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Skip code CI tests if the PR only contains docs change to save time

### Solution

pick flink repo

### Anything else?

no

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
+++1 666
