### ISSUE TITLE
[Bug] FileStoreBatchE2eTest failed on azure CI

### ISSUE THREAD

**Issue by leonardBang** [apache/incubator-paimon#653]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

d44741d6aaa43a73a20ef96979a8ded72efc2f6c

### Compute Engine

Flink

### Minimal reproduce step

https://github.com/apache/incubator-paimon/actions/runs/4464527298/jobs/7840743848

### What doesn't meet your expectations?

result

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by klion26** [comment]
maybe [support infer parallelism for flink table store](https://github.com/apache/incubator-paimon/pull/584) can solve this problem
