### ISSUE TITLE
[Document] Add document for hdfs and recommend to use the computing engine's own filesystem

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#664]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

- Add doc for hdfs
- recommend to use the computing engine's own filesystem, like flink with own fs, spark with hadoop fs, hive with hadoop fs.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by SteNicholas** [comment]
@liugddx, welcome to contribute. I have assigned this issue to you.
