### ISSUE TITLE
[Feature]  Introduce Presto Reader for Paimon

### ISSUE THREAD

**Issue by s7monk** [apache/incubator-paimon#667]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Introduce Presto Reader for Paimon

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
This can be closed since a new repo for presto has been created:
https://github.com/apache/incubator-paimon-presto
