### ISSUE TITLE
[Feature] Optimize serialization of TableSchema

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#679]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Now the serialization of TableSchema is more violent, once it is determined that there are watermark or calculated columns, is to turn all schema into options stuffed into.
We should only serialize watermark and calculated columns.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by hililiwei** [comment]
I'm interested in this. May I have the ticket?

**Comment by yuzelin** [comment]
@hililiwei Sorry for late response. This issue is solved by https://github.com/apache/incubator-paimon/pull/1041
