### ISSUE TITLE
[Bug] Assign all splits in one time will produce exceed `akka.framesize` to exceptions in StaticFileStoreSplitEnumerator

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#681]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.4

### Compute Engine

flink

### Minimal reproduce step

This in the case of a very large number of partitions + buckets.

### What doesn't meet your expectations?

exception of exceeding `akka.framesize`.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
This is rely on https://github.com/apache/incubator-paimon/pull/680

**Comment by FangYongs** [comment]
Fixed by #687
