### ISSUE TITLE
[Improvement] Add validating column type in ddl for different format

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#682]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Current paimon use avro/orc/parquet to store data which only support some of data type in sql. Paimon should validate the data type supported by format in ddl, otherwise the ddl will be successful and writing jobs will fail.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by SteNicholas** [comment]
@hk-lrzy, welcome to contribute. I have assigned this issue to you.
