### ISSUE TITLE
[Bug] Remove dependency to sun.misc.*

### ISSUE THREAD

**Issue by innovimax** [apache/incubator-paimon#692]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

all version

### Compute Engine

all

### Minimal reproduce step

build with a JDK that is not provided by Oracle

### What doesn't meet your expectations?

I cannot build this with another JDK that the one provided by Oracle

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Can you specify where is the dependency?

**Comment by innovimax** [comment]
using the search is how you can see it
https://github.com/search?q=repo%3Aapache%2Fincubator-paimon+sun.misc&type=code

**Comment by tsreaper** [comment]
Hi! Thanks for reporting this issue. Which JDK and maven version are you using? What command are you using to compile the project? What error message occurs? Please provide detailed information.

**Comment by innovimax** [comment]
Last OpenJDK 19
maven build
Error is saying that sun.misc.* is not available

No idea on how to mitigate this so far, but I think this is a general issue and perhaps Apache has a generic answer ?

**Comment by ericxiao251** [comment]
Not sure what IDE you are using @innovimax, but I was able to fix this issue by unchecking this setting in IntelliJ:
![image](https://user-images.githubusercontent.com/9758510/231347074-9263d9c8-5b1a-41d2-9961-37ad3848d67a.png)

**Comment by innovimax** [comment]
Hi @ericxiao251 
It doesn't fix it (since it was already checked on my Intellij IDEA)

Furthermore, it's a more general question about depending on a non public API (sun.misc.Unsafe)

**Comment by innovimax** [comment]
@JingsongLi I don't see how this is fixed ?
