### ISSUE TITLE
[Feature] Some problems with stream reading

### ISSUE THREAD

**Issue by siyangzeng** [apache/incubator-paimon#699]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Q1：
When I am reading incremental streams, if I use the parameter "scan.timestamp-millis", 
when the snapshot corresponding to the timestamp expires, an error will be reported. 
I think there should be a bottom-back policy : 
scan.timestamp-millis < snapshot earliest timestamp, then read from EARLIEST
scan.timestamp-millis > snapshot latest timestamp, then scans-mode = 'latest'

Q2：
The parallelism is greater than the number of buckets during stream read, and the excess slots are not used

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tsreaper** [comment]
Hi! Thanks for reporting this issue. However I'd like to discuss your questions a bit more.

In Q1 you mentioned that

> when the snapshot corresponding to the timestamp expires, an error will be reported

What error is reported under what condition? Could you explain what you're doing in detail when the error occurs? Could you add a complete exception stack in the issue description?

You also mentioned that

> scan.timestamp-millis > snapshot latest timestamp, then scans-mode = 'latest'

As far as I remember, our current implementation has exactly the same effect. Is the actual behavior different? If yes, what is the actual behavior?

In Q2 you said that

> The parallelism is greater than the number of buckets during stream read, and the excess slots are not used

This is expected for Flink sources. Users should either decrease the source parallelism or change bucket number to a larger value. Or are you suggesting something different? What would you like to suggest for this scenario?

**Comment by wxplovecc** [comment]
Hi @tsreaper in Q1, user start streaming read give some fixed timestamp in sql, but if the the sql task restart then the error occurs
and in Q2 it`s expected in non partitioned table but for partiton table stream read should shuffle by partitons maybe

**Comment by FangYongs** [comment]
Thanks @wxplovecc Which version are you using? Can you give the exception stack about Q1?
If I understand correctly, you submit a streaming job with paimon source which reads incremental data. If the source tasks of job restarted due to the failover, I think it will be restored with snapshot and splits from state instead of the fixed timestamp. 

Of course, jobs may use memory state and source tasks will read from the fixed timestamp after restarted. But as @tsreaper mentioned above,  the source subtask should read specific snapshot according to the timestamp from paimon without exception.

**Comment by FangYongs** [comment]
@wxplovecc What's the strategy do you mean for restarting without state? Could you describe it in detail? If a job has no state, I think it will calculate snapshot id according to the fixed timestamp without throwing an exception after restart

**Comment by wxplovecc** [comment]
@FangYongs Maybe like this 
`scan.timestamp-millis` < snapshot earliest timestamp, then read from EARLIEST
`scan.timestamp-millis` > snapshot latest timestamp, then scans-mode = 'latest'
when the fixed timestamp was illegality

**Comment by FangYongs** [comment]
As @tsreaper mentioned above, I think the current strategy of `scan.timestamp-millis` in paimon is just as you described:

scan.timestamp-millis < snapshot earliest timestamp, then read from EARLIEST
scan.timestamp-millis > snapshot latest timestamp, then scans-mode = 'latest'

If it doesn't act as above, I think it's a bug

**Comment by tsreaper** [comment]
> 

Paimon Flink connector already supports this feature. If you set `sink.partition-shuffle` to true then the records will be shuffled both by bucket and by partition. See https://paimon.apache.org/docs/master/maintenance/configurations/#flinkconnectoroptions for more detail.

@JingsongLi maybe we should remove this option and always shuffle by both bucket and partition. I don't see any disadvantage if we do so.

**Comment by wxplovecc** [comment]
@FangYongs I think so.  Below was the stack 
![企业微信截图_16800578569914](https://user-images.githubusercontent.com/3350718/228413526-b373be4f-c31d-4145-8122-8cc15ea0be5e.png)

**Comment by JingsongLi** [comment]
> > it`s expected in non partitioned table but for partiton table stream read should shuffle by partitons maybe
> 
> Paimon Flink connector already supports this feature. If you set `sink.partition-shuffle` to true then the records will be shuffled both by bucket and by partition. See https://paimon.apache.org/docs/master/maintenance/configurations/#flinkconnectoroptions for more detail.
> 
> @JingsongLi maybe we should remove this option and always shuffle by both bucket and partition. I don't see any disadvantage if we do so.

Sink has already supported it, but source dose not.

**Comment by siyangzeng** [comment]
done

**Comment by siyangzeng** [comment]
done

**Comment by siyangzeng** [comment]
done
