### ISSUE TITLE
[Bug] LogStoreTableFactory should not implements DynamicTableFactory

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#705]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.4

### Compute Engine

flink

### Minimal reproduce step

kafka connector sink to paimon table

### What doesn't meet your expectations?

Now, KafkaLogStoreFactory is very easy to conflict with flink kafka connector.
we should not use flink DynamicTableFactory.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by legendtkl** [comment]
@JingsongLi  Do you mean when we use kafka connector in the job, it will find LogStoreTableFactory as kafka connector?

**Comment by SteNicholas** [comment]
@Alibaba-HZY, welcome to contribute. Please go ahead to fix the bug.

**Comment by JingsongLi** [comment]
The https://github.com/apache/incubator-paimon/pull/729 is valid.
But we need to go ahead and complete the issue.
The core reason is that if there is no kafka jar in flink/lib, the kafka identifier will find `KafkaLogStoreFactory` in paimon, and throw `KafkaLogStoreFactory is not a DynamicTableSourceFactory` exception, which is very confused.

**Comment by Alibaba-HZY** [comment]
> The #729 is valid. But we need to go ahead and complete the issue. The core reason is that if there is no kafka jar in flink/lib, the kafka identifier will find `KafkaLogStoreFactory` in paimon, and throw `KafkaLogStoreFactory is not a DynamicTableSourceFactory` exception, which is very confused.

ok i know i will remove DynamicTableFactory in LogStoreTableFactory
