### ISSUE TITLE
[Feature] Flink connector should use public API

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#706]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Now, Flink connector uses FileStoreTable, this is not public api, we should just use public api Table.
This is rely on https://github.com/apache/incubator-paimon/issues/638

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
I'd like to take this.

**Comment by zhuangchong** [comment]
@yuzelin Hello, if this PR has not started, can you assign it to me.

**Comment by zhuangchong** [comment]
@JingsongLi This pr has been done, you can close this issue.
