### ISSUE TITLE
[Improve] Add the renameDatabase method to the Catalog interface and implement this method

### ISSUE THREAD

**Issue by s7monk** [apache/incubator-paimon#716]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Is it necessary to add the renameDatabase method to the Catalog interface?

I think it is possible to rename database sometimes.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tsreaper** [comment]
Glad that you're willing to implement this feature. +1 for this.
