### ISSUE TITLE
[Feature] Assign batch splits for ContinuousFileSplitEnumerator

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#722]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

#687 introduces an option `scan.split-enumerator.batch-size` for assigning splits at one time to avoid exceed `akka.framesize` limit in `StaticFileStoreSplitEnumerator`. `ContinuousFileSplitEnumerator` should support this mechanism too.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wxplovecc** [comment]
Hi @FangYongs  Assign this to me .

**Comment by yuzelin** [comment]
This is solved, please close~
