### ISSUE TITLE
[Feature] Get rid of flink-connector-hive dependency in paimon-hive

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#737]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

It is unnecessary for the tablestore to rely on it in the test. Its incompatible modifications will make the tablestore troublesome.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
Can you assign it to me?
