### ISSUE TITLE
[Feature] Spark writer supports insert overwrite

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#738]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Spark writer supports insert overwrite

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tobehardest** [comment]
can you assign me this task?

**Comment by JingsongLi** [comment]
@tobehardest Just create a PR for this.

**Comment by JingsongLi** [comment]
Unassigned because that haven't replied for a long time
