### ISSUE TITLE
[Feature] Optimize SortMergeReader: use loser tree to reduce comparisons

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#741]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

See https://en.wikipedia.org/wiki/K-way_merge_algorithm

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liming30** [comment]
@JingsongLi hi, I'm interested in this, can it be assigned to me if no one else is doing it?
