### ISSUE TITLE
[Feature] More metrics for flink table store

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#742]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

TODO add more metrics, we should the detail requirement.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by schnappi17** [comment]
Hi @JingsongLi I'm willing to take this, and we're planning this also.

**Comment by schnappi17** [comment]
> We can add some metrics on Paimon's memory usage.

Thanks @wg1026688210 for your suggestion, is there any memory usage problem in Paimon you encounterd?

**Comment by schnappi17** [comment]
Create a PIP here https://cwiki.apache.org/confluence/display/PAIMON/PIP-3%3A+Introduce+metrics+for+Paimon, update in progress...

**Comment by wg1026688210** [comment]
> 

hi~ @schnappi17  I encountered an OOM problem during the compaction, it was resolved later. Therefore, I think users can more easily discover issues, if Paimon has  memory-related metrics.

**Comment by FangYongs** [comment]
DONE
