### ISSUE TITLE
[Feature] Flink Catalog supports partition methods

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#747]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Flink Catalog can support:
listPartitions
listPartitionsByFilter
getPartition
partitionExists
dropPartition

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xuzhiwen1255** [comment]
Hi, can you assign it to me?

**Comment by felixYyu** [comment]
I also want to finish it.

**Comment by ericxiao251** [comment]
Hi, I would like to work on this as well.

**Comment by JingsongLi** [comment]
Hi @ericxiao251 , we just need to implement functions in `FlinkCatalog`, for example, for `listPartitions`, it is similiar to `PartitionExpire.readPartitions`, here we need to convert `BinaryRow`s to `CatalogPartitionSpec`s.

**Comment by liugddx** [comment]
https://github.com/apache/iceberg/pull/1815/files

**Comment by ericxiao251** [comment]
👋🏼 thanks @liugddx and @JingsongLi for the direction! I wasn't able to leverage the `BinaryRow` class, but was able to use the `InternalRow` class.

Would either of you have a chance to look at the initial implementation and let me know if I am on the right track? It looks like a lot more code than some of the examples both of you've listed, so i am not sure if I have overcomplicated anything.

**Comment by leaves12138** [comment]
We can realize listPartitions method and dropPartition method in Paimon Catalog

**Comment by zhuangchong** [comment]
This pr has been done, I will close this issue.
