### ISSUE TITLE
[Feature] Introduce Hive writer

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#752]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Introduce Hive writer

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by TyrantLucifer** [comment]
I'm interested in it. Could you please assign it to me?

**Comment by JingsongLi** [comment]
@Alibaba-HZY Assigned to u, maybe we can have a write-only version for hive writer.
