### ISSUE TITLE
[Feature] Use ci to check the document markdown link

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-paimon#756]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

markdown link error in the document

### Solution

Use ci to check the document markdown link

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
@JingsongLi  Does the paimon project need this check?

**Comment by JingsongLi** [comment]
> @JingsongLi Does the paimon project need this check?

Maybe we don't need this check, it is too strict.
