### ISSUE TITLE
[Feature] Replace flink-shaded-guava and flink-shaded-jackson with paimon-shade

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-paimon#757]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Avoid jar dependency conflicts

### Solution

Replace flink-shade-guave and flink-shade-jackson with paimon-shade

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
Done by https://github.com/apache/incubator-paimon/pull/838
