### ISSUE TITLE
[Feature] provide a flink option to chose which log to read from

### ISSUE THREAD

**Issue by nonggialiang** [apache/incubator-paimon#778]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

For now, a paimon table can keep log both in file store and external log system at the same time , by setting log.system=kafka and changelog-producer=input/full-compaction at the same time.
But at the source side, if log.system=kafka is set, the continues read is bound to kafka, and file store log will be ignored. 
Since log of file store can support some feature that external log system doesn't support, like full-changelog, I think it's reasonable to provide a option for user to chose which log to read from.

### Solution

Provide a flink option scan.log.from=external/internal, or sth like that to expose both choices.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Alibaba-HZY** [comment]
I have interest to work for this issue. Please assign this issue to me.
