### ISSUE TITLE
[Feature] Fix column comments for flink-1.17

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#784]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

subtask of #640 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by schnappi17** [comment]
@FangYongs I'm willing to take this task, please help to assign to me if no one else is doing on this, thanks~
