### ISSUE TITLE
[Feature] Integrate alter table for flink-1.17

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#785]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

subtask of #640

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by schnappi17** [comment]
@FangYongs Please assign this to me, thanks~

**Comment by ericxiao251** [comment]
@schnappi17 do you think I can take this task, I noticed you got assigned this task https://github.com/apache/incubator-paimon/issues/784 already :P.

**Comment by schnappi17** [comment]
@ericxiao251 Hi Eric, I'm developing on this task already, sorry for the missing information syncing.

**Comment by FangYongs** [comment]
@schnappi17 assigned, thanks @ericxiao251 and welcome to help review this PR
