### ISSUE TITLE
[Feature] Implements SourceReader.pauseOrResumeSplit for flink-1.17

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#788]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

subtask of #640 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liming30** [comment]
@FangYongs I'm interested in this, please assign me if no one else is doing it.
