### ISSUE TITLE
[Feature] Upgrade flink.md to use flink-1.17

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#789]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

subtask of #640 
1. Add flink-1.17 related jar path
2. Add operations supported flink-1.17, such as kill job in console

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by schnappi17** [comment]
@FangYongs Please help to assign this to me, I'm interested on this~

**Comment by zhuangchong** [comment]
This is already a pr: #783
