### ISSUE TITLE
[Feature] MemoryFileStoreWrite in flink sink allocate segment from flink managed memory

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#796]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Currently MemoryFileStoreWrite allocate memory pool from heap for sink writer. It should allocate segments from MemoryManager for flink sink.

### Solution

PIP: https://cwiki.apache.org/confluence/display/PAIMON/PIP-1%3A+Improve+Shared+Writer+Buffer+Pool+For+Sink

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zoucao** [comment]
I am willing to try this ticket, counld you assign it to me

**Comment by FangYongs** [comment]
Thanks @zoucao. I considered this issue overall and thought it was a big feature. We should review the memory usage in merge tree and will give a design in PIP. I will create subtasks after that and please feel free to take them

**Comment by zoucao** [comment]
> Thanks @zoucao. I considered this issue overall and thought it was a big feature. We should review the memory usage in merge tree and will give a design in PIP. I will create subtasks after that and please feel free to take them

Hi @FangYongs, Thanks for your kind advice, and I am looking forward to your design.

**Comment by zhuangchong** [comment]
The related PR has been merged and I will close this issue.
