### ISSUE TITLE
[Bug] Hive does not Pass filesystem config  to FileIO 

### ISSUE THREAD

**Issue by wg1026688210** [apache/incubator-paimon#798]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

hive 

### Minimal reproduce step

create hive external table

### What doesn't meet your expectations?

FileIO receive the config from hive 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
> I'm willing to submit a PR

Thanks, assigned to you.
