### ISSUE TITLE
[Feature] support alluxio filesystem in paimon

### ISSUE THREAD

**Issue by qics1982** [apache/incubator-paimon#802]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

alluxio is a data orchestration technology(https://docs.alluxio.io/os/user/stable/en/Overview.html),
we mainly use alluxio to speet up hot (hive/iceberg) tables which are frequenty accessed for lookup join or ad-hot query via trino.

similar to hdfs, we can create and  use paimon catalogs in alluxio,

alluxio releted configurations can be configured in hdfs core-site.xml or in catalog propreties

create catalog in flink:
CREATE CATALOG my_catalog WITH (
    'type' = 'paimon',
    'warehouse' = 'alluxio://path/to/warehouse'
);
USE CATALOG my_catalog;

then  wen can create/write to paimon tables in Flink/Spark, and read paimon tables  in Flink/Spark/Trino side

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
Related PR: #797
