### ISSUE TITLE
[Feature] support hive-conf-dir and hadoop-conf-dir option in hive catalog

### ISSUE THREAD

**Issue by Alibaba-HZY** [apache/incubator-paimon#823]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

If kerberos authentication is enabled for the hive, the catalog cannot be created. because hiveMetastoreClient init requires a hive-site.xml configuration file.so users can specify the path to the configuration file according to hive-conf-dir and hadoop-conf-dir

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Alibaba-HZY** [comment]
I have interest to work for this issue. Please assign this issue to me.

**Comment by JingsongLi** [comment]
@Alibaba-HZY assigned to u, thanks!
