### ISSUE TITLE
[Feature]  Avoid using hive's own FileSystem to access the location of paimon table

### ISSUE THREAD

**Issue by wg1026688210** [apache/incubator-paimon#830]
### Search before asking

- [x] I searched in the [[[issues](https://github.com/apache/incubator-paimon/issues)](https://github.com/apache/incubator-paimon/issues)](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

When using a permission authentication policy based on `StorageBasedAuthorizationProvider`, creating an external table of  paimon will cause Hive to create its own FileSystem to access the  location of paimon table in object storage , and it will not read the configuration of paimon for accessing the object storage .

### Solution

- Extend  `StorageBasedAuthorizationProvider` for checking whether is paimon table through the `STORED BY` field of table

- Support multi strategy for  permission authentication  policy of paimon if the  table is stored by paimon :

  - strategy 1 : do nothing for permission authentication checking  

  - strategy 2 :using  paimon's filesystem for checking permission authentication , the following is what we need to do

    - get the configuration of paimon for accessing the object storage 

      support the catalog property of paimon's extern table like Iceberg , so that we can access the config of object storage .  For example  : 

     ```sql
     CREATE EXTERNAL TABLE my_table
     STORED BY 'org.apache.paimon.hive.PaimonStorageHandler'
     LOCATION 's3://realtime/wgcn/warehouse/default.db/word_count';
     TBLPROPERTIES ('paimon.catalog'='a1');
     ```

     

    ​	and then we can get the catalog info from the config of HMS like:

    

    ```xml
        <property>
            <name>paimon.catalog.a1.access.key</name>
            <value>...</value>
        </property>
        <property>
            <name>paimon.catalog.a1.secret.key</name>
            <value>...</value>
        </property>
    ```

    ​	 or somewhere user redefine

    - use  the paimon's filesystem and implement the  permission authentication  Refering to the implementation of `StorageBasedAuthorizationProvider`

- add the document for guiding users config the  extend  of StorageBasedAuthorizationProvider at HMS

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by wg1026688210** [comment]
I'm willing to submit a PR

**Comment by JingsongLi** [comment]
@wg1026688210 Thanks, assigned to u~

**Comment by zhuangchong** [comment]
The relevant PR has been merged and I will close this issue.
