### ISSUE TITLE
[Feature] Document Flink Table API and conversion between Table and DataStream

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#850]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

https://github.com/apache/incubator-paimon/issues/723 document Java API.
We can have more documentation about Flink programing.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by SYG-ATONE** [comment]
I am willing to try this ticket, counld you assign it to me，thanks
