### ISSUE TITLE
[Bug] Drop table will cause file leak with inserting jobs still running

### ISSUE THREAD

**Issue by schnappi17** [apache/incubator-paimon#870]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master: fb9babbb8676d598e817704db4993604b0d3a9d6

### Compute Engine

Flink 1.16.1

### Minimal reproduce step

1. create table
2. insert into table
3. drop table

### What doesn't meet your expectations?

This will leave some data files and manifest folder there, and an abnormal insert job failover always. 

### Anything else?

I think we should reject dropping operation on table which is being written at that time, or at least we could document that stop the inserting jobs before you drop a paimon table.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
@JingsongLi is me.

**Comment by JingsongLi** [comment]
I think it is hard to Reject dropping operation.
It is OK to just document the right dropping behavior.
