### ISSUE TITLE
[Feature] Support consume group id like kafka

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#881]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Consume group id in kafka is useful for restarting without state.
We can use files to record consume group id too.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lilyzhoupeijie** [comment]
hi @JingsongLi ,I would like to work on this. Would you help assign this to me? thanks.

**Comment by SteNicholas** [comment]
@lilyzhoupeijie, assigned to you. Go ahead to contribute this support.

**Comment by JingsongLi** [comment]
> hi @JingsongLi ,I would like to work on this. Would you help assign this to me? thanks.

Hi @lilyzhoupeijie ,  I started related work, and if you have the energy you can continue to improve it on my base.

**Comment by lilyzhoupeijie** [comment]
@JingsongLi  I have seen the logic of consumer-id, it's great and will work fine.so if there is a consumer group,is there some idea on how to separate the data into different consumers within this  consumer group? and the info about group still store in /tablePath/consumer/consumer-*?

**Comment by JingsongLi** [comment]
> @JingsongLi I have seen the logic of consumer-id, it's great and will work fine.so if there is a consumer group,is there some idea on how to separate the data into different consumers within this consumer group? and the info about group still store in /tablePath/consumer/consumer-*?

Replied in the PR.
