### ISSUE TITLE
[Feature] Introduce file.compression

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#889]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Add a generic configuration: `file.compression`, which is used by default, replace orc.compress and parquet.compression. Then file.compression.per.level can override the compression of the specified level.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Tartarus0zm** [comment]
I would like to take this issue,  please assign to me, thanks~ @JingsongLi

**Comment by tsreaper** [comment]
Since #914 is causing failure in unit tests I've reverted the PR.
