### ISSUE TITLE
[Feature] Support Hive CREATE TABLE

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-paimon#901]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Support Hive CREATE TABLE

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Alibaba-HZY** [comment]
I have interest to work for this issue. Please assign this issue to me.

**Comment by zhuangchong** [comment]
@Alibaba-HZY Sorry for late response. I'v done some work about this.

**Comment by Alibaba-HZY** [comment]
> @Alibaba-HZY Sorry for late response. I'v done some work about this.
it doesn't matter.
