### ISSUE TITLE
[Feature] Reduce memory use when scan manifests

### ISSUE THREAD

**Issue by wxplovecc** [apache/incubator-paimon#907]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Too many memory use of List objects when scan manifests
![8071c29043ea96545213d58082a4ac98](https://user-images.githubusercontent.com/3350718/231926540-46642d6f-5aa7-4045-b417-8125acc5dbe1.png)

### Solution

Change List to Iterator

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Fixed by https://github.com/apache/incubator-paimon/pull/1072
