### ISSUE TITLE
[Bug] Unit test failed with error message "native lz4 library not available"

### ISSUE THREAD

**Issue by liming30** [apache/incubator-paimon#923]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.4-snapshot

### Compute Engine

flink-1.16

### Minimal reproduce step

mvn test -pl paimon-format -Dtest=org.apache.paimon.format.parquet.ParquetReadWriteTest#testContinuousRepetition

### What doesn't meet your expectations?

There should be no exceptions.

### Anything else?
![image](https://user-images.githubusercontent.com/69444450/232384779-1009e81a-c5f5-4d15-8303-faf67c518d35.png)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by liming30** [comment]
@Tartarus0zm Can you please help to confirm this issue? It seems to be caused by this [change](https://github.com/apache/incubator-paimon/commit/9965bf00f25146d8c190b4aa4626dad1033c9838#diff-bd68be8f7a92b6893f7c9712fb3ac174ebc0865f4321b8572db968a5acceb6c5). When I changed it from `LZ4` to `SNAPPY`, the error disappeared.

**Comment by liming30** [comment]
@JingsongLi The compression type of `LZ4` uses hadoop's native library. Should we change the compression type in the test to the default `UNCOMPRESSED` or other compression types?

**Comment by JingsongLi** [comment]
Thanks @liming30 , file compression pr reverted.
