### ISSUE TITLE
[Feature] Remove warning in `mvn clean install`

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#942]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

`[WARNING] /Users/ljs/IdeaProjects/paimon/paimon-common/src/main/java/org/apache/paimon/data/JoinedRow.java:57: 警告 - 不能在inline文档中使用标记@param。只能在以下类型的文档中使用该标记: class/interface, constructor, method。`

When running `mvn clean install`, there are lots of warning.
We can fix them to reduce warning.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liugddx** [comment]
assign to me thanks.

**Comment by zhuangchong** [comment]
This pr is done and I will close this issue.
