### ISSUE TITLE
[Improve] Unified command line parameters

### ISSUE THREAD

**Issue by liugddx** [apache/incubator-paimon#950]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

close #949 

I found that there are a lot of repeated codes in the command line parsing through action, and some parameters need to be parsed separately. I recommend using jcommander for this part of the job.

### Solution

1. Use jcommander to unify console parameters
2. Remove duplicate code
3. Optimized help tips

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by liugddx** [comment]
@JingsongLi  Do we need this part of the optimization? For example, partition configuration partition=key1=value1,key2=value2. Now we can use partition=key1=value1 key2=value2, there is also no need to parse it separately in the code, just need this ```     @DynamicParameter(
            names = {"--partition"},
            description = "partition key value pair, for example key1=value1 key2=value2")
    private Map<String, String> partition;```

**Comment by liugddx** [comment]
![image](https://user-images.githubusercontent.com/48236177/233272088-97eacf4f-c143-46a3-a26b-a9762ca5f889.png)

At present, there will be no friendly prompts for parsing parameter exceptions.

**Comment by liugddx** [comment]
At present, the command line parameters are scattered in the method
![image](https://user-images.githubusercontent.com/48236177/233272978-925ad117-827b-4b44-89f9-3f058dfc101a.png)
This is deceptive. We can define parameters as parameters of action, like 
<img width="939" alt="ef99be7a10c7d634fdb0135719a1484" src="https://user-images.githubusercontent.com/48236177/233273276-ab5ff77f-abdd-451b-b53d-c3ce05c92dd3.png">
this is more maintenance-friendly.

**Comment by liugddx** [comment]
3. At present, the definition of usage is manually written, which is more detailed but also brings maintenance complexity. We can automatically generate usage through jcommander. Of course, jcommander also provides the ability to customize usage.

**Comment by liugddx** [comment]
@JingsongLi @SteNicholas Can you give me some advice. I'd be happy to parameterize this function

**Comment by JingsongLi** [comment]
I think this is a good improvement, but I don't think our Actions are so complicated.
I think we can use this later, in the event of a problem occurring, there is no apparent problem at this time

**Comment by liugddx** [comment]
> I think this is a good improvement, but I don't think our Actions are so complicated. I think we can use this later, in the event of a problem occurring, there is no apparent problem at this time

I agree with you.
