### ISSUE TITLE
[Improve] Use auto-service optimize SPI registration

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/incubator-paimon#956]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Now paimon use the origin method to load SPI such as `org.apache.paimon.fs.FileIOLoader`, `auto-service` is a good tool to use annotation to genreate `META-INT/services/xxxxxx` automatic when compile stage.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Thanks @TyrantLucifer for reporting. 

Maybe it is not the time.
Currently, our SPIs are simple, we don't need to introduce a mechanism to make this complex.
