### ISSUE TITLE
[Feature] support more mysql data type for Mysql CDC Sync Action

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/incubator-paimon#966]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Now, flink mysql cdc connector support all mysql data type ,
https://ververica.github.io/flink-cdc-connectors/master/content/connectors/mysql-cdc.html#data-type-mapping
we should also support them in the mysql cdc action. 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhangjun0x01** [comment]
> @zhangjun0x01 Are we done with all the types?

the `set` type has not done ,I am doing some test.

**Comment by JingsongLi** [comment]
Thanks @zhangjun0x01 !
