### ISSUE TITLE
[Feature] Disable ChangelogValueCountFileStoreTable by default

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#973]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

We can disable `ChangelogValueCountFileStoreTable` by default.
Most of users want to use append-only mode.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
Can you assign it to me? Thanks.
