### ISSUE TITLE
[Feature] Add a mechanism to judge whether to apply filter pushdown

### ISSUE THREAD

**Issue by yuzelin** [apache/incubator-paimon#989]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Take new `DELETE` syntax in Flink 1.17 as a instance.
The flink sink can implement `SupportsDeletePushDown`. But when should the sink apply pushdown? 
In my opinion, if the filter is very simple, such as delete one row, delete whole table, the cost of pushdown is low; but if the filter is too complex, the cost of pushdown maybe high, so it's better to let flink to do the job.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by legendtkl** [comment]
hi, @yuzelin , I would like to continue to work on the ticket for the follow-up of DELETE.

**Comment by yuzelin** [comment]
@legendtkl Thanks. Can you give some thoughts about this ticket? Or we can have some discussion about how to implement this. I think we should have some draft before doing it.

**Comment by legendtkl** [comment]
> @legendtkl Thanks. Can you give some thoughts about this ticket? Or we can have some discussion about how to implement this. I think we should have some draft before doing it.

Yes, discussion is necessary. I need more context about this. Let's discuss this later.
