### ISSUE TITLE
[Bug] 【doc】Table name[MyTable] cannot contain upper case

### ISSUE THREAD

**Issue by ymZhao1001** [apache/incubator-paimon#990]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.4

### Compute Engine

flink

### Minimal reproduce step

CREATE CATALOG my_hive WITH (
>     'type' = 'paimon',
>     'metastore' = 'hive',
>     'uri' = 'thrift://***:9083',
>     'warehouse' = 'hdfs://***/user/zym/paimon'
> );

Flink SQL> USE CATALOG my_hive;
[INFO] Execute statement succeed.

CREATE TABLE MyTable (
>     user_id BIGINT,
>     item_id BIGINT,
>     behavior STRING,
>     dt STRING,
>     hh STRING,
>     PRIMARY KEY (dt, hh, user_id) NOT ENFORCED
> );
[ERROR] Could not execute SQL statement. Reason:
java.lang.IllegalStateException: Table name[MyTable] cannot contain upper case

### What doesn't meet your expectations?

hive catalog org.apache.paimon.hive.HiveCatalog#checkIdentifierUpperCase  ;

do we need to change the table name "MyTable" to lowercase "my_table"?

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ymZhao1001** [comment]
hi @JingsongLi  ,do you thinke it is necessary? if not ,i will close this one

**Comment by JingsongLi** [comment]
> hi @JingsongLi ,do you thinke it is necessary? if not ,i will close this one

This is because Flink dose not support case insensetive mode...

**Comment by JingsongLi** [comment]
We can close this. The only way is using lower case

**Comment by JingsongLi** [comment]
We should document this in https://paimon.apache.org/docs/master/how-to/creating-catalogs/#creating-a-catalog-with-hive-metastore

**Comment by ymZhao1001** [comment]
Flink SQL> CREATE TABLE my_table (
>     user_id BIGINT,
>     item_id BIGINT,
>     behavior STRING,
>     dt STRING,
>     hh STRING,
>     PRIMARY KEY (dt, hh, user_id) NOT ENFORCED
> ) PARTITIONED BY (dt, hh);
[INFO] Execute statement succeed.

Flink SQL> ALTER TABLE my_table RENAME TO MyTable;
[INFO] Execute statement succeed.

**Comment by ymZhao1001** [comment]
@JingsongLi  need to checkTableNamesUpperCase in renameTable
